#line 2 "Lexer.C"

#line 4 "Lexer.C"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define partial_bnfc_acsl_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer partial_bnfc_acsl_create_buffer
#endif

#ifdef yy_delete_buffer
#define partial_bnfc_acsl_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer partial_bnfc_acsl_delete_buffer
#endif

#ifdef yy_scan_buffer
#define partial_bnfc_acsl_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer partial_bnfc_acsl_scan_buffer
#endif

#ifdef yy_scan_string
#define partial_bnfc_acsl_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string partial_bnfc_acsl_scan_string
#endif

#ifdef yy_scan_bytes
#define partial_bnfc_acsl_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes partial_bnfc_acsl_scan_bytes
#endif

#ifdef yy_init_buffer
#define partial_bnfc_acsl_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer partial_bnfc_acsl_init_buffer
#endif

#ifdef yy_flush_buffer
#define partial_bnfc_acsl_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer partial_bnfc_acsl_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define partial_bnfc_acsl_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state partial_bnfc_acsl_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define partial_bnfc_acsl_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer partial_bnfc_acsl_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define partial_bnfc_acslpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state partial_bnfc_acslpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define partial_bnfc_acslpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state partial_bnfc_acslpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define partial_bnfc_acslensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack partial_bnfc_acslensure_buffer_stack
#endif

#ifdef yylex
#define partial_bnfc_acsllex_ALREADY_DEFINED
#else
#define yylex partial_bnfc_acsllex
#endif

#ifdef yyrestart
#define partial_bnfc_acslrestart_ALREADY_DEFINED
#else
#define yyrestart partial_bnfc_acslrestart
#endif

#ifdef yylex_init
#define partial_bnfc_acsllex_init_ALREADY_DEFINED
#else
#define yylex_init partial_bnfc_acsllex_init
#endif

#ifdef yylex_init_extra
#define partial_bnfc_acsllex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra partial_bnfc_acsllex_init_extra
#endif

#ifdef yylex_destroy
#define partial_bnfc_acsllex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy partial_bnfc_acsllex_destroy
#endif

#ifdef yyget_debug
#define partial_bnfc_acslget_debug_ALREADY_DEFINED
#else
#define yyget_debug partial_bnfc_acslget_debug
#endif

#ifdef yyset_debug
#define partial_bnfc_acslset_debug_ALREADY_DEFINED
#else
#define yyset_debug partial_bnfc_acslset_debug
#endif

#ifdef yyget_extra
#define partial_bnfc_acslget_extra_ALREADY_DEFINED
#else
#define yyget_extra partial_bnfc_acslget_extra
#endif

#ifdef yyset_extra
#define partial_bnfc_acslset_extra_ALREADY_DEFINED
#else
#define yyset_extra partial_bnfc_acslset_extra
#endif

#ifdef yyget_in
#define partial_bnfc_acslget_in_ALREADY_DEFINED
#else
#define yyget_in partial_bnfc_acslget_in
#endif

#ifdef yyset_in
#define partial_bnfc_acslset_in_ALREADY_DEFINED
#else
#define yyset_in partial_bnfc_acslset_in
#endif

#ifdef yyget_out
#define partial_bnfc_acslget_out_ALREADY_DEFINED
#else
#define yyget_out partial_bnfc_acslget_out
#endif

#ifdef yyset_out
#define partial_bnfc_acslset_out_ALREADY_DEFINED
#else
#define yyset_out partial_bnfc_acslset_out
#endif

#ifdef yyget_leng
#define partial_bnfc_acslget_leng_ALREADY_DEFINED
#else
#define yyget_leng partial_bnfc_acslget_leng
#endif

#ifdef yyget_text
#define partial_bnfc_acslget_text_ALREADY_DEFINED
#else
#define yyget_text partial_bnfc_acslget_text
#endif

#ifdef yyget_lineno
#define partial_bnfc_acslget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno partial_bnfc_acslget_lineno
#endif

#ifdef yyset_lineno
#define partial_bnfc_acslset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno partial_bnfc_acslset_lineno
#endif

#ifdef yyget_column
#define partial_bnfc_acslget_column_ALREADY_DEFINED
#else
#define yyget_column partial_bnfc_acslget_column
#endif

#ifdef yyset_column
#define partial_bnfc_acslset_column_ALREADY_DEFINED
#else
#define yyset_column partial_bnfc_acslset_column
#endif

#ifdef yywrap
#define partial_bnfc_acslwrap_ALREADY_DEFINED
#else
#define yywrap partial_bnfc_acslwrap
#endif

#ifdef yyget_lval
#define partial_bnfc_acslget_lval_ALREADY_DEFINED
#else
#define yyget_lval partial_bnfc_acslget_lval
#endif

#ifdef yyset_lval
#define partial_bnfc_acslset_lval_ALREADY_DEFINED
#else
#define yyset_lval partial_bnfc_acslset_lval
#endif

#ifdef yyget_lloc
#define partial_bnfc_acslget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc partial_bnfc_acslget_lloc
#endif

#ifdef yyset_lloc
#define partial_bnfc_acslset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc partial_bnfc_acslset_lloc
#endif

#ifdef yyalloc
#define partial_bnfc_acslalloc_ALREADY_DEFINED
#else
#define yyalloc partial_bnfc_acslalloc
#endif

#ifdef yyrealloc
#define partial_bnfc_acslrealloc_ALREADY_DEFINED
#else
#define yyrealloc partial_bnfc_acslrealloc
#endif

#ifdef yyfree
#define partial_bnfc_acslfree_ALREADY_DEFINED
#else
#define yyfree partial_bnfc_acslfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define partial_bnfc_acslwrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 143
#define YY_END_OF_BUFFER 144
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[564] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  144,  142,  141,  141,   24,  127,   59,    9,
       31,   32,   28,   56,   17,   57,  142,   58,  139,   16,
        1,   18,  142,   19,   15,  140,   29,  142,   30,   11,
      142,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,   66,   10,
       67,   60,  143,  130,  129,  128,  137,  135,  136,  131,
      132,  133,  134,   23,    7,    0,   68,    0,  139,    0,
       20,   22,   21,  140,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,

        0,  140,  140,  140,   75,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,    6,   12,
      138,    0,    0,    4,    0,   62,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   14,    0,    0,    0,    0,
        0,    0,   65,    0,    0,    0,    0,    0,    0,    0,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,   93,  140,  140,
      140,  140,  140,  140,  100,  140,  140,  140,  105,  140,

      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,    0,   13,
        5,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,    0,
        0,    0,    0,    0,    0,    0,    0,  140,  140,  140,
      140,  140,  140,  140,  140,  140,   82,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  107,  108,  140,
      140,  140,  140,  140,  114,  140,  140,  140,  140,  140,
      140,  140,  122,  140,  140,  125,  140,    0,  138,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    0,    0,   55,    0,    0,    0,    0,    0,
        0,   33,    0,    0,   69,   70,  140,  140,  140,  140,
       76,  140,  140,  140,   83,  140,  140,  140,  140,  140,
      140,  140,   91,   92,   94,  140,  140,  140,  140,  140,
      140,  140,  103,  104,  106,  109,  140,  140,  140,  113,
      140,  140,  117,  140,  140,  120,  140,  140,  140,  140,
        0,    0,    0,    0,    0,    0,    0,   34,    0,    0,
       43,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   36,  140,   72,  140,  140,  140,  140,  140,   81,

      140,  140,  140,  140,  140,   89,  140,  140,   96,   97,
      140,  140,  140,  140,  110,  111,  140,  140,  140,  118,
      119,  140,  140,  140,  126,    0,    0,    0,    0,    0,
        0,   26,   25,    0,    0,   27,    0,    0,   46,    0,
       63,    0,   53,    0,    0,  140,   73,   74,  140,  140,
       80,  140,  140,  140,  140,  140,   90,  140,   98,  140,
      101,  140,  140,  140,  116,  140,  140,  124,    0,    0,
        0,    0,    0,    0,   51,    0,    0,    3,    0,    0,
        0,    0,    0,    0,    0,  140,  140,   78,   84,  140,
       86,  140,   88,   95,  140,  140,  140,  115,  140,  123,

        0,    0,    0,    0,    0,   42,   48,    0,    0,   52,
        0,    0,    0,    0,    0,    0,   71,   77,   79,   85,
       87,   99,  102,  112,  140,   47,    0,   50,   44,    0,
        0,    0,   64,    0,    0,    0,    0,    0,  121,   49,
        0,    0,    0,    0,    0,    0,    0,   37,    0,   41,
        0,   54,    0,   39,   40,   45,    0,    0,    0,    0,
       35,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    2,    2,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[568] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   58,   59,
       62,   63,  581,  582,  582,  582,  559,  582,  582,  572,
      582,  582,  582,  582,  582,  564,  562,  582,   54,  582,
      582,   56,  555,  554,  582,    0,  582,   83,  582,  545,
      548,   38,   46,   37,   39,   29,   94,  530,   52,   85,
      526,  522,  534,   62,   68,  524,   48,  519,  582,  508,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  543,  582,  547,  109,  549,
      541,  539,  582,    0,   96,   66,  106,  506,  109,  515,
      527,   98,  116,  518,  521,  106,  507,  510,  522,  582,

      507,  508,  508,  500,    0,  509,  509,  501,  510,   74,
      107,  511,  494,  491,  492,  501,  494,  490,  502,  492,
      490,  488,  126,  501,  112,  126,  498,  133,  122,  486,
       65,  491,  481,  482,  478,  478,  486,  485,  582,  582,
      148,  501,  500,  582,  479,  582,  470,  470,  473,  473,
      472,  476,  472,  465,  132,  473,  468,  460,  467,  468,
      471,  472,  582,  136,  459,  473,  452,  471,  459,  455,
      460,  453,  140,  452,  465,  453,  463,  445,  459,  445,
      440,  441,  448,  455,  435,  435,  453,    0,  448,  449,
      449,  449,  437,  427,  442,  445,  440,  431,    0,  434,

      435,  425,  131,  433,  435,  146,  417,  416,  418,  421,
      429,  430,  419,  426,  421,  420,  424,  407,  167,  582,
      582,  411,  410,  419,  420,  415,  420,  401,  400,  417,
      151,  404,  396,  413,  406,  401,  407,  392,  582,  401,
      388,  407,  387,  401,  393,  395,  391,  382,  398,  382,
      392,  385,  384,  374,  390,  383,    0,  382,  380,  148,
      386,  375,  377,  370,  368,  366,  366,  364,  382,  379,
      360,  377,  372,  360,  365,  375,  372,    0,    0,  362,
      361,  359,  362,  351,    0,  360,  350,  347,  361,  350,
      359,  354,    0,  355,  360,    0,  355,  372,  371,  354,

      343,  355,  343,  341,  339,  331,  345,  337,  347,  339,
      582,  337,  341,  335,  582,  340,  337,  322,  328,  321,
      329,  582,  325,  332,  582,    0,  334,  314,  319,  327,
      330,  321,  328,  309,    0,  322,  312,  324,  323,  314,
      317,  316,    0,    0,    0,  311,  307,  298,  313,  296,
      310,  305,    0,    0,    0,    0,  308,  311,  308,    0,
      292,  295,    0,  304,  301,    0,  292,  291,  290,  284,
      301,  300,  299,  299,  289,  288,  277,  582,  283,  292,
      582,  292,  291,  277,  270,  269,  268,  267,  285,  282,
      269,  283,  262,    0,  262,  261,  259,  263,  263,    0,

      256,  254,  271,  254,  258,    0,  252,  255,    0,    0,
      264,  259,  249,  265,    0,    0,  264,  259,  244,    0,
        0,  261,  256,  240,    0,  142,  239,  254,  245,  242,
      252,  582,  582,  242,  241,  582,  245,  251,  582,  245,
      582,  229,  582,  245,  154,  242,    0,    0,  237,  227,
        0,  239,  238,  222,  236,  220,    0,  225,    0,  216,
        0,  223,  216,  216,    0,  214,  229,    0,  220,  222,
      221,  225,  223,  220,  582,  221,  216,  582,  208,  205,
      217,  220,  199,  205,  163,  199,  214,  197,    0,  196,
        0,  195,    0,    0,  208,  192,  206,    0,  205,    0,

      204,  193,  204,  188,  191,  582,  582,  178,  188,  582,
      198,  181,  186,  195,  184,  196,    0,    0,    0,    0,
        0,    0,    0,    0,  177,  582,  181,  582,  582,  187,
      188,  183,  582,  186,  187,  184,  181,  183,    0,  582,
      166,  181,  170,  179,  162,  157,  175,  582,  171,  582,
      151,  582,  160,  582,  582,  582,  162,  150,  141,  100,
      582,  582,  582,  202,  204,  206,   74
    } ;

static const flex_int16_t yy_def[568] =
    {   0,
      563,    1,  564,  564,  564,  564,  564,  564,  565,  565,
      566,  566,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  567,  563,  563,  563,  563,
      563,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  567,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,

      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  567,  567,  567,  567,  567,  567,  567,  567,

      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  567,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,    0,  563,  563,  563,  563
    } ;

static const flex_int16_t yy_nxt[643] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   14,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   36,   49,   36,
       36,   50,   51,   36,   36,   52,   36,   53,   54,   55,
       56,   57,   58,   36,   36,   36,   59,   60,   61,   62,
       63,   63,   65,   65,   63,   63,   68,   68,   78,   80,
       79,  102,  115,  112,  110,   84,   81,  113,  136,  103,
      107,  111,  116,  114,   66,   66,  104,  105,   69,   69,
      108,  106,  137,  109,  122,  123,  148,   70,   70,  130,

      131,  210,  133,  132,  178,   71,   71,  149,  179,   72,
       72,   73,   73,   85,   86,  124,   87,   88,   89,  125,
      211,   90,  134,   78,   91,   79,   92,   93,   94,  126,
       95,   96,   97,   98,   99,  117,  150,  145,  118,  153,
      165,  119,  158,  562,  120,  146,  147,  160,  159,  180,
      181,  161,  206,  154,  198,  166,  155,  162,  193,  194,
      151,  199,  200,  204,  141,  280,  231,  205,  207,  201,
      202,  208,  240,  469,  250,  195,  232,  196,  251,  284,
      298,  281,  219,  299,  241,  309,  337,  285,  561,  483,
      252,  470,  484,  515,  560,  338,  559,  516,  558,  310,

      557,  485,   63,   63,   64,   64,   67,   67,  556,  555,
      554,  553,  552,  551,  550,  549,  548,  547,  546,  545,
      544,  543,  542,  541,  540,  539,  538,  537,  536,  535,
      534,  533,  532,  531,  530,  529,  528,  527,  526,  525,
      524,  523,  522,  521,  520,  519,  518,  517,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,

      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  299,  299,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,

      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  283,  282,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  249,  248,  247,

      246,  245,  244,  243,  242,  239,  238,  237,  236,  235,
      234,  233,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  218,  217,  216,  215,  214,  213,  212,
      209,  203,  197,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  164,  163,  157,  156,  152,
      144,  143,  142,  141,  140,  139,  138,  135,  129,  128,
      127,  121,  101,  100,   83,   82,   77,   76,   75,   74,
      563,   13,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563
    } ;

static const flex_int16_t yy_chk[643] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   10,    9,   10,   11,   12,   11,   12,   29,   32,
       29,   42,   46,   45,   44,  567,   32,   45,   57,   42,
       43,   44,   46,   45,    9,   10,   42,   42,   11,   12,
       43,   42,   57,   43,   49,   49,   86,   11,   12,   54,

       54,  131,   55,   54,  110,   11,   12,   86,  110,   11,
       12,   11,   12,   38,   38,   50,   38,   38,   38,   50,
      131,   38,   55,   79,   38,   79,   38,   38,   38,   50,
       38,   38,   38,   38,   38,   47,   87,   85,   47,   89,
       96,   47,   92,  560,   47,   85,   85,   93,   92,  111,
      111,   93,  129,   89,  125,   96,   89,   93,  123,  123,
       87,  125,  126,  128,  141,  203,  155,  128,  129,  126,
      126,  129,  164,  426,  173,  123,  155,  123,  173,  206,
      219,  203,  141,  219,  164,  231,  260,  206,  559,  445,
      173,  426,  445,  485,  558,  260,  557,  485,  553,  231,

      551,  445,  564,  564,  565,  565,  566,  566,  549,  547,
      546,  545,  544,  543,  542,  541,  538,  537,  536,  535,
      534,  532,  531,  530,  527,  525,  516,  515,  514,  513,
      512,  511,  509,  508,  505,  504,  503,  502,  501,  499,
      497,  496,  495,  492,  490,  488,  487,  486,  484,  483,
      482,  481,  480,  479,  477,  476,  474,  473,  472,  471,
      470,  469,  467,  466,  464,  463,  462,  460,  458,  456,
      455,  454,  453,  452,  450,  449,  446,  444,  442,  440,
      438,  437,  435,  434,  431,  430,  429,  428,  427,  424,
      423,  422,  419,  418,  417,  414,  413,  412,  411,  408,

      407,  405,  404,  403,  402,  401,  399,  398,  397,  396,
      395,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  380,  379,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  365,  364,  362,  361,
      359,  358,  357,  352,  351,  350,  349,  348,  347,  346,
      342,  341,  340,  339,  338,  337,  336,  334,  333,  332,
      331,  330,  329,  328,  327,  324,  323,  321,  320,  319,
      318,  317,  316,  314,  313,  312,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      295,  294,  292,  291,  290,  289,  288,  287,  286,  284,

      283,  282,  281,  280,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  259,  258,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      238,  237,  236,  235,  234,  233,  232,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  205,  204,
      202,  201,  200,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  172,  171,  170,

      169,  168,  167,  166,  165,  162,  161,  160,  159,  158,
      157,  156,  154,  153,  152,  151,  150,  149,  148,  147,
      145,  143,  142,  138,  137,  136,  135,  134,  133,  132,
      130,  127,  124,  122,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  109,  108,  107,  106,  104,  103,
      102,  101,   99,   98,   97,   95,   94,   91,   90,   88,
       82,   81,   80,   78,   76,   60,   58,   56,   53,   52,
       51,   48,   41,   40,   34,   33,   27,   26,   20,   17,
       13,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "partial_bnfc_acsl_parser.l"
/* -*- c++ -*- File generated by the BNF Converter (bnfc 2.9.4.1). */
/* Lexer definition for use with FLex */
#define YY_NO_INPUT 1
/* Additional data for the lexer: a buffer for lexing string literals. */
#line 13 "partial_bnfc_acsl_parser.l"
#include "Absyn.H"
#include "Bison.H"

#define initialize_lexer partial_bnfc_acsl_initialize_lexer

/* BEGIN extensible string buffer */

#include "Buffer.H"

/* The initial size of the buffer to lex string literals. */
#define LITERAL_BUFFER_INITIAL_SIZE 1024

/* The pointer to the literal buffer. */
#define literal_buffer yyextra

/* Initialize the literal buffer. */
#define LITERAL_BUFFER_CREATE() literal_buffer = newBuffer(LITERAL_BUFFER_INITIAL_SIZE)

/* Append characters at the end of the buffer. */
#define LITERAL_BUFFER_APPEND(s) bufferAppendString(literal_buffer, s)

/* Append a character at the end of the buffer. */
#define LITERAL_BUFFER_APPEND_CHAR(c) bufferAppendChar(literal_buffer, c)

/* Release the buffer, returning a pointer to its content. */
#define LITERAL_BUFFER_HARVEST() releaseBuffer(literal_buffer)

/* In exceptional cases, e.g. when reaching EOF, we have to free the buffer. */
#define LITERAL_BUFFER_FREE() freeBuffer(literal_buffer)

/* END extensible string buffer */

static void update_loc(YYLTYPE* loc, char* text)
{
  loc->first_line = loc->last_line;
  loc->first_column = loc->last_column;
  int i = 0;
  for (; text[i] != '\0'; ++i) {
      if (text[i] == '\n') {
          ++loc->last_line;
          loc->last_column = 0;
      } else {
          ++loc->last_column;
      }
  }
}
#define YY_USER_ACTION update_loc(yylloc, yytext);

#line 1037 "Lexer.C"

#line 1039 "Lexer.C"

#define INITIAL 0
#define CHAR 1
#define CHARESC 2
#define CHAREND 3
#define STRING 4
#define ESCAPED 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE Buffer

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 70 "partial_bnfc_acsl_parser.l"


#line 1327 "Lexer.C"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 564 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 582 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "partial_bnfc_acsl_parser.l"
return _SEMI;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "partial_bnfc_acsl_parser.l"
return _SYMB_1;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "partial_bnfc_acsl_parser.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "partial_bnfc_acsl_parser.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "partial_bnfc_acsl_parser.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 77 "partial_bnfc_acsl_parser.l"
return _DBAR;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 78 "partial_bnfc_acsl_parser.l"
return _DAMP;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 79 "partial_bnfc_acsl_parser.l"
return _DCARET;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 80 "partial_bnfc_acsl_parser.l"
return _AMP;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 81 "partial_bnfc_acsl_parser.l"
return _BAR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 82 "partial_bnfc_acsl_parser.l"
return _CARET;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 83 "partial_bnfc_acsl_parser.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 84 "partial_bnfc_acsl_parser.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 85 "partial_bnfc_acsl_parser.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 86 "partial_bnfc_acsl_parser.l"
return _QUESTION;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 87 "partial_bnfc_acsl_parser.l"
return _COLON;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 88 "partial_bnfc_acsl_parser.l"
return _COMMA;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 89 "partial_bnfc_acsl_parser.l"
return _LT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 90 "partial_bnfc_acsl_parser.l"
return _GT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 91 "partial_bnfc_acsl_parser.l"
return _LDARROW;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 92 "partial_bnfc_acsl_parser.l"
return _GTEQ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "partial_bnfc_acsl_parser.l"
return _DEQ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 94 "partial_bnfc_acsl_parser.l"
return _BANGEQ;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 95 "partial_bnfc_acsl_parser.l"
return _BANG;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "partial_bnfc_acsl_parser.l"
return _SYMB_24;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "partial_bnfc_acsl_parser.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "partial_bnfc_acsl_parser.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "partial_bnfc_acsl_parser.l"
return _STAR;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "partial_bnfc_acsl_parser.l"
return _LBRACK;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "partial_bnfc_acsl_parser.l"
return _RBRACK;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 102 "partial_bnfc_acsl_parser.l"
return _LPAREN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "partial_bnfc_acsl_parser.l"
return _RPAREN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "partial_bnfc_acsl_parser.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "partial_bnfc_acsl_parser.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "partial_bnfc_acsl_parser.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "partial_bnfc_acsl_parser.l"
return _SYMB_35;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "partial_bnfc_acsl_parser.l"
return _SYMB_36;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "partial_bnfc_acsl_parser.l"
return _SYMB_37;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "partial_bnfc_acsl_parser.l"
return _SYMB_38;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "partial_bnfc_acsl_parser.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 112 "partial_bnfc_acsl_parser.l"
return _SYMB_40;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "partial_bnfc_acsl_parser.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 114 "partial_bnfc_acsl_parser.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 115 "partial_bnfc_acsl_parser.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 116 "partial_bnfc_acsl_parser.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 117 "partial_bnfc_acsl_parser.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "partial_bnfc_acsl_parser.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "partial_bnfc_acsl_parser.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "partial_bnfc_acsl_parser.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 121 "partial_bnfc_acsl_parser.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 122 "partial_bnfc_acsl_parser.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 123 "partial_bnfc_acsl_parser.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 124 "partial_bnfc_acsl_parser.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 125 "partial_bnfc_acsl_parser.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 126 "partial_bnfc_acsl_parser.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 127 "partial_bnfc_acsl_parser.l"
return _PLUS;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 128 "partial_bnfc_acsl_parser.l"
return _MINUS;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 129 "partial_bnfc_acsl_parser.l"
return _SLASH;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "partial_bnfc_acsl_parser.l"
return _PERCENT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 131 "partial_bnfc_acsl_parser.l"
return _TILDE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 132 "partial_bnfc_acsl_parser.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 133 "partial_bnfc_acsl_parser.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "partial_bnfc_acsl_parser.l"
return _SYMB_62;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 135 "partial_bnfc_acsl_parser.l"
return _SYMB_63;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "partial_bnfc_acsl_parser.l"
return _SYMB_64;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 137 "partial_bnfc_acsl_parser.l"
return _LBRACE;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 138 "partial_bnfc_acsl_parser.l"
return _RBRACE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 139 "partial_bnfc_acsl_parser.l"
return _DDOT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "partial_bnfc_acsl_parser.l"
return _SYMB_68;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "partial_bnfc_acsl_parser.l"
return _KW_admit;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "partial_bnfc_acsl_parser.l"
return _KW_allocates;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "partial_bnfc_acsl_parser.l"
return _KW_assert;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "partial_bnfc_acsl_parser.l"
return _KW_assigns;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "partial_bnfc_acsl_parser.l"
return _KW_assumes;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "partial_bnfc_acsl_parser.l"
return _KW_at;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 147 "partial_bnfc_acsl_parser.l"
return _KW_axiom;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 148 "partial_bnfc_acsl_parser.l"
return _KW_axiomatic;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 149 "partial_bnfc_acsl_parser.l"
return _KW_behavior;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 150 "partial_bnfc_acsl_parser.l"
return _KW_behaviors;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 151 "partial_bnfc_acsl_parser.l"
return _KW_boolean;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 152 "partial_bnfc_acsl_parser.l"
return _KW_breaks;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 153 "partial_bnfc_acsl_parser.l"
return _KW_char;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 154 "partial_bnfc_acsl_parser.l"
return _KW_check;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 155 "partial_bnfc_acsl_parser.l"
return _KW_complete;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 156 "partial_bnfc_acsl_parser.l"
return _KW_continues;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 157 "partial_bnfc_acsl_parser.l"
return _KW_contract;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 158 "partial_bnfc_acsl_parser.l"
return _KW_decreases;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 159 "partial_bnfc_acsl_parser.l"
return _KW_disjoint;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 160 "partial_bnfc_acsl_parser.l"
return _KW_double;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 161 "partial_bnfc_acsl_parser.l"
return _KW_ensures;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 162 "partial_bnfc_acsl_parser.l"
return _KW_exits;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 163 "partial_bnfc_acsl_parser.l"
return _KW_float;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 164 "partial_bnfc_acsl_parser.l"
return _KW_for;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 165 "partial_bnfc_acsl_parser.l"
return _KW_frees;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 166 "partial_bnfc_acsl_parser.l"
return _KW_function;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 167 "partial_bnfc_acsl_parser.l"
return _KW_global;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 168 "partial_bnfc_acsl_parser.l"
return _KW_impact;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 169 "partial_bnfc_acsl_parser.l"
return _KW_include;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 170 "partial_bnfc_acsl_parser.l"
return _KW_inductive;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 171 "partial_bnfc_acsl_parser.l"
return _KW_int;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 172 "partial_bnfc_acsl_parser.l"
return _KW_integer;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 173 "partial_bnfc_acsl_parser.l"
return _KW_invariant;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 174 "partial_bnfc_acsl_parser.l"
return _KW_label;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 175 "partial_bnfc_acsl_parser.l"
return _KW_lemma;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 176 "partial_bnfc_acsl_parser.l"
return _KW_let;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 177 "partial_bnfc_acsl_parser.l"
return _KW_logic;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 178 "partial_bnfc_acsl_parser.l"
return _KW_long;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 179 "partial_bnfc_acsl_parser.l"
return _KW_loop;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 180 "partial_bnfc_acsl_parser.l"
return _KW_model;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 181 "partial_bnfc_acsl_parser.l"
return _KW_module;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 182 "partial_bnfc_acsl_parser.l"
return _KW_pragma;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 183 "partial_bnfc_acsl_parser.l"
return _KW_predicate;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 184 "partial_bnfc_acsl_parser.l"
return _KW_reads;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 185 "partial_bnfc_acsl_parser.l"
return _KW_real;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 186 "partial_bnfc_acsl_parser.l"
return _KW_requires;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 187 "partial_bnfc_acsl_parser.l"
return _KW_returns;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 188 "partial_bnfc_acsl_parser.l"
return _KW_short;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 189 "partial_bnfc_acsl_parser.l"
return _KW_signed;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 190 "partial_bnfc_acsl_parser.l"
return _KW_sizeof;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 191 "partial_bnfc_acsl_parser.l"
return _KW_slice;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 192 "partial_bnfc_acsl_parser.l"
return _KW_terminates;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 193 "partial_bnfc_acsl_parser.l"
return _KW_type;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 194 "partial_bnfc_acsl_parser.l"
return _KW_unsigned;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 195 "partial_bnfc_acsl_parser.l"
return _KW_variant;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 196 "partial_bnfc_acsl_parser.l"
return _KW_void;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 197 "partial_bnfc_acsl_parser.l"
return _KW_writes;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 201 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_CREATE(); BEGIN STRING;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 202 "partial_bnfc_acsl_parser.l"
BEGIN ESCAPED;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 203 "partial_bnfc_acsl_parser.l"
yylval->_string = LITERAL_BUFFER_HARVEST(); BEGIN INITIAL; return _STRING_;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 204 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR(yytext[0]);
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 205 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR('\f'); BEGIN STRING;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 206 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR('\n'); BEGIN STRING;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 207 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR('\r'); BEGIN STRING;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 208 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR('\t'); BEGIN STRING;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 209 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR('"');  BEGIN STRING;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 210 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND_CHAR('\\'); BEGIN STRING;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 211 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_APPEND(yytext);    BEGIN STRING;
	YY_BREAK
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
#line 212 "partial_bnfc_acsl_parser.l"
LITERAL_BUFFER_FREE(); return _ERROR_;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 213 "partial_bnfc_acsl_parser.l"
yylval->_double = atof(yytext); return _DOUBLE_;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 214 "partial_bnfc_acsl_parser.l"
yylval->_int = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 215 "partial_bnfc_acsl_parser.l"
yylval->_string = strdup(yytext); return _IDENT_;
	YY_BREAK
case 141:
/* rule 141 can match eol */
YY_RULE_SETUP
#line 216 "partial_bnfc_acsl_parser.l"
/* ignore white space. */;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 217 "partial_bnfc_acsl_parser.l"
return _ERROR_;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 219 "partial_bnfc_acsl_parser.l"
ECHO;
	YY_BREAK
#line 2105 "Lexer.C"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 564 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 564 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 563);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 219 "partial_bnfc_acsl_parser.l"


yyscan_t initialize_lexer(FILE *inp)
{
  yyscan_t scanner;
  if (yylex_init_extra(NULL, &scanner)) return 0;
  if (inp) yyrestart(inp, scanner);
  return scanner;
}


