/* File generated by the BNF Converter (bnfc 2.9.4.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2

namespace acsl
{
//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitListIdent(ListIdent *listident)
{
  iterListIdent(listident->begin(), listident->end());
}

void PrintAbsyn::iterListIdent(ListIdent::const_iterator i, ListIdent::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    visitIdent(*i);
  }
  else
  { /* cons */
    visitIdent(*i); render(','); iterListIdent(i+1, j);
  }
}

void PrintAbsyn::visitMain(Main *p) {} //abstract class

void PrintAbsyn::visitAMain(AMain *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; visitListAnOption(p->listanoption_);
  _i_ = 0; visitListMetavar(p->listmetavar_);
  _i_ = 0; visitListState(p->liststate_);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAnOption(AnOption *p) {} //abstract class

void PrintAbsyn::visitOption(Option *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('%');
  visitIdent(p->ident_);
  _i_ = 0; p->optidentifiers_->accept(this);
  render(';');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListAnOption(ListAnOption *listanoption)
{
  iterListAnOption(listanoption->begin(), listanoption->end());
}

void PrintAbsyn::iterListAnOption(ListAnOption::const_iterator i, ListAnOption::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); iterListAnOption(i+1, j);
  }
}

void PrintAbsyn::visitOptIdentifiers(OptIdentifiers *p) {} //abstract class

void PrintAbsyn::visitEmptyOptIdent(EmptyOptIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);


  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOptIdent(OptIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render(':');
  _i_ = 0; visitListIdent(p->listident_);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMetavar(Metavar *p) {} //abstract class

void PrintAbsyn::visitAMetavar(AMetavar *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('$');
  visitIdent(p->ident_1);
  render(':');
  visitIdent(p->ident_2);
  render(';');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListMetavar(ListMetavar *listmetavar)
{
  iterListMetavar(listmetavar->begin(), listmetavar->end());
}

void PrintAbsyn::iterListMetavar(ListMetavar::const_iterator i, ListMetavar::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListMetavar(i+1, j);
  }
}

void PrintAbsyn::visitState(State *p) {} //abstract class

void PrintAbsyn::visitAState(AState *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; visitListTransition(p->listtransition_);
  render(';');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListState(ListState *liststate)
{
  iterListState(liststate->begin(), liststate->end());
}

void PrintAbsyn::iterListState(ListState::const_iterator i, ListState::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); iterListState(i+1, j);
  }
}

void PrintAbsyn::visitTransition(Transition *p) {} //abstract class

void PrintAbsyn::visitEmptyTransition(EmptyTransition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);


  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSeqTransition(SeqTransition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('{');
  _i_ = 0; p->seqelt_->accept(this);
  render('}');
  _i_ = 0; visitListAction(p->listaction_);
  render("->");
  visitIdent(p->ident_);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOtherTransition(OtherTransition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render("other");
  _i_ = 0; visitListAction(p->listaction_);
  render("->");
  visitIdent(p->ident_);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSimpleTransition(SimpleTransition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; visitListAction(p->listaction_);
  render("->");
  visitIdent(p->ident_);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListTransition(ListTransition *listtransition)
{
  iterListTransition(listtransition->begin(), listtransition->end());
}

void PrintAbsyn::iterListTransition(ListTransition::const_iterator i, ListTransition::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render('|'); iterListTransition(i+1, j);
  }
}

void PrintAbsyn::visitGuard(Guard *p) {} //abstract class

void PrintAbsyn::visitGuardSquares(GuardSquares *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('[');
  _i_ = 0; visitListSeqElt(p->listseqelt_);
  render(']');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGuardWithPreEmpty(GuardWithPreEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  visitIdent(p->ident_);
  _i_ = 0; p->precond_->accept(this);
  render('(');
  render(')');
  _i_ = 0; p->postcond_->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGuardWithPre(GuardWithPre *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  visitIdent(p->ident_);
  _i_ = 0; p->precond_->accept(this);
  render('(');
  _i_ = 0; visitListSeqElt(p->listseqelt_);
  render(')');
  _i_ = 0; p->postcond_->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGuardPostOnly(GuardPostOnly *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  visitIdent(p->ident_);
  render('(');
  _i_ = 0; visitListSeqElt(p->listseqelt_);
  render(')');
  _i_ = 0; p->postcond_->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGuardPostOnlyEmpty(GuardPostOnlyEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  visitIdent(p->ident_);
  render('(');
  render(')');
  _i_ = 0; p->postcond_->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPreCond(PreCond *p) {} //abstract class

void PrintAbsyn::visitPrecondCC(PrecondCC *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render("::");
  visitIdent(p->ident_);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPrecondBB(PrecondBB *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render("{{");
  _i_ = 0; p->cond_->accept(this);
  render("}}");

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPostCond(PostCond *p) {} //abstract class

void PrintAbsyn::visitPostcondEmpty(PostcondEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);


  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPostcondSimple(PostcondSimple *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render("{{");
  _i_ = 0; p->cond_->accept(this);
  render("}}");

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSeqElt(SeqElt *p) {} //abstract class

void PrintAbsyn::visitSeqEltCond(SeqEltCond *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->cond_->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSeqEltGuardRep(SeqEltGuardRep *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->guard_->accept(this);
  _i_ = 0; p->repetition_->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListSeqElt(ListSeqElt *listseqelt)
{
  iterListSeqElt(listseqelt->begin(), listseqelt->end());
}

void PrintAbsyn::iterListSeqElt(ListSeqElt::const_iterator i, ListSeqElt::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(';'); iterListSeqElt(i+1, j);
  }
}

void PrintAbsyn::visitRepetition(Repetition *p) {} //abstract class

void PrintAbsyn::visitRepetitionEmpty(RepetitionEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);


  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionPlus(RepetitionPlus *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('+');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionMinus(RepetitionMinus *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('*');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionQuestion(RepetitionQuestion *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('?');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionPair(RepetitionPair *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('{');
  _i_ = 0; p->expr_1->accept(this);
  render(',');
  _i_ = 0; p->expr_2->accept(this);
  render('}');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionOne(RepetitionOne *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('{');
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionREmpty(RepetitionREmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('{');
  _i_ = 0; p->expr_->accept(this);
  render(',');
  render('}');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRepetitionLEmpty(RepetitionLEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('{');
  render(',');
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCond(Cond *p) {} //abstract class

void PrintAbsyn::visitLogicOr(LogicOr *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 1; p->cond_1->accept(this);
  render("||");
  _i_ = 0; p->cond_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicAnd(LogicAnd *p)
{
  int oldi = _i_;
  if (oldi > 1) render(ACSL__L_PAREN);

  _i_ = 2; p->cond_1->accept(this);
  render("&&");
  _i_ = 1; p->cond_2->accept(this);

  if (oldi > 1) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitACondCOR(ACondCOR *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  render("COR");
  render('(');
  visitIdent(p->ident_);
  render(')');

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitACondCALL(ACondCALL *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  render("CALL");
  render('(');
  visitIdent(p->ident_);
  render(')');

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitACondReturn(ACondReturn *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  render("RETURN");
  render('(');
  visitIdent(p->ident_);
  render(')');

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitACondTrue(ACondTrue *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  render("true");

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitACondFalse(ACondFalse *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  render("false");

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitACondNot(ACondNot *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  render('!');
  _i_ = 2; p->cond_->accept(this);

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationCond(RelationCond *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  _i_ = 0; p->logicrelation_->accept(this);

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicRelation(LogicRelation *p) {} //abstract class

void PrintAbsyn::visitLogicEQ(LogicEQ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render("==");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicLess(LogicLess *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render('<');
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicGreater(LogicGreater *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render('>');
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicLessEQ(LogicLessEQ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render("<=");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicGreaterEQ(LogicGreaterEQ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render(">=");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicNotEQ(LogicNotEQ *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render("!=");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpr(Expr *p) {} //abstract class

void PrintAbsyn::visitAdd(Add *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  render('+');
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSubtract(Subtract *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  render('-');
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDivide(Divide *p)
{
  int oldi = _i_;
  if (oldi > 1) render(ACSL__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  render('/');
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 1) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMultiply(Multiply *p)
{
  int oldi = _i_;
  if (oldi > 1) render(ACSL__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  render('*');
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 1) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMod(Mod *p)
{
  int oldi = _i_;
  if (oldi > 1) render(ACSL__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  render('%');
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 1) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBitAnd(BitAnd *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render('&');
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBitOr(BitOr *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render('|');
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBitXor(BitXor *p)
{
  int oldi = _i_;
  if (oldi > 2) render(ACSL__L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render('^');
  _i_ = 3; p->expr_2->accept(this);

  if (oldi > 2) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInt(Int *p)
{
  int oldi = _i_;
  if (oldi > 3) render(ACSL__L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 3) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFloat(Float *p)
{
  int oldi = _i_;
  if (oldi > 3) render(ACSL__L_PAREN);

  visitDouble(p->double_);

  if (oldi > 3) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNegativeInt(NegativeInt *p)
{
  int oldi = _i_;
  if (oldi > 3) render(ACSL__L_PAREN);

  render('-');
  visitInteger(p->integer_);

  if (oldi > 3) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNegativeDouble(NegativeDouble *p)
{
  int oldi = _i_;
  if (oldi > 3) render(ACSL__L_PAREN);

  render('-');
  visitDouble(p->double_);

  if (oldi > 3) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStructFielsAccess(StructFielsAccess *p)
{
  int oldi = _i_;
  if (oldi > 4) render(ACSL__L_PAREN);

  _i_ = 4; p->expr_->accept(this);
  render('.');
  visitIdent(p->ident_);

  if (oldi > 4) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPointerAccess(PointerAccess *p)
{
  int oldi = _i_;
  if (oldi > 4) render(ACSL__L_PAREN);

  _i_ = 4; p->expr_->accept(this);
  render("->");
  visitIdent(p->ident_);

  if (oldi > 4) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayAccess(ArrayAccess *p)
{
  int oldi = _i_;
  if (oldi > 4) render(ACSL__L_PAREN);

  _i_ = 4; p->expr_1->accept(this);
  render('[');
  _i_ = 3; p->expr_2->accept(this);
  render(']');

  if (oldi > 4) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRefAccess(RefAccess *p)
{
  int oldi = _i_;
  if (oldi > 5) render(ACSL__L_PAREN);

  render('*');
  _i_ = 4; p->expr_->accept(this);

  if (oldi > 5) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunAccess(FunAccess *p)
{
  int oldi = _i_;
  if (oldi > 5) render(ACSL__L_PAREN);

  visitIdent(p->ident_1);
  render('(');
  render(')');
  render('.');
  visitIdent(p->ident_2);

  if (oldi > 5) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIdentifier(Identifier *p)
{
  int oldi = _i_;
  if (oldi > 5) render(ACSL__L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 5) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMetavarAccess(MetavarAccess *p)
{
  int oldi = _i_;
  if (oldi > 5) render(ACSL__L_PAREN);

  render('$');
  visitIdent(p->ident_);

  if (oldi > 5) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAction(Action *p) {} //abstract class

void PrintAbsyn::visitAnAction(AnAction *p)
{
  int oldi = _i_;
  if (oldi > 0) render(ACSL__L_PAREN);

  render('$');
  visitIdent(p->ident_);
  render(":=");
  _i_ = 0; p->expr_->accept(this);
  render(';');

  if (oldi > 0) render(ACSL__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListAction(ListAction *listaction)
{
  iterListAction(listaction->begin(), listaction->end());
}

void PrintAbsyn::iterListAction(ListAction::const_iterator i, ListAction::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListAction(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}


ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitListIdent(ListIdent *listident)
{
  for (ListIdent::const_iterator i = listident->begin() ; i != listident->end() ; ++i)
  {
    visitIdent(*i) ;
    if (i != listident->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitMain(Main *p) {} //abstract class

void ShowAbsyn::visitAMain(AMain *p)
{
  bufAppend('(');
  bufAppend("AMain");
  bufAppend(' ');
  bufAppend('[');
  if (p->listanoption_)  p->listanoption_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listmetavar_)  p->listmetavar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststate_)  p->liststate_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAnOption(AnOption *p) {} //abstract class

void ShowAbsyn::visitOption(Option *p)
{
  bufAppend('(');
  bufAppend("Option");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->optidentifiers_)  p->optidentifiers_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListAnOption(ListAnOption *listanoption)
{
  for (ListAnOption::const_iterator i = listanoption->begin() ; i != listanoption->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listanoption->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitOptIdentifiers(OptIdentifiers *p) {} //abstract class

void ShowAbsyn::visitEmptyOptIdent(EmptyOptIdent *p)
{
  bufAppend("EmptyOptIdent");
}
void ShowAbsyn::visitOptIdent(OptIdent *p)
{
  bufAppend('(');
  bufAppend("OptIdent");
  bufAppend(' ');
  bufAppend('[');
  if (p->listident_)  p->listident_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitMetavar(Metavar *p) {} //abstract class

void ShowAbsyn::visitAMetavar(AMetavar *p)
{
  bufAppend('(');
  bufAppend("AMetavar");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListMetavar(ListMetavar *listmetavar)
{
  for (ListMetavar::const_iterator i = listmetavar->begin() ; i != listmetavar->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listmetavar->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitState(State *p) {} //abstract class

void ShowAbsyn::visitAState(AState *p)
{
  bufAppend('(');
  bufAppend("AState");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listtransition_)  p->listtransition_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListState(ListState *liststate)
{
  for (ListState::const_iterator i = liststate->begin() ; i != liststate->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != liststate->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitTransition(Transition *p) {} //abstract class

void ShowAbsyn::visitEmptyTransition(EmptyTransition *p)
{
  bufAppend("EmptyTransition");
}
void ShowAbsyn::visitSeqTransition(SeqTransition *p)
{
  bufAppend('(');
  bufAppend("SeqTransition");
  bufAppend(' ');
  bufAppend('[');
  if (p->seqelt_)  p->seqelt_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listaction_)  p->listaction_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitOtherTransition(OtherTransition *p)
{
  bufAppend('(');
  bufAppend("OtherTransition");
  bufAppend(' ');
  bufAppend('[');
  if (p->listaction_)  p->listaction_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitSimpleTransition(SimpleTransition *p)
{
  bufAppend('(');
  bufAppend("SimpleTransition");
  bufAppend(' ');
  bufAppend('[');
  if (p->listaction_)  p->listaction_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitListTransition(ListTransition *listtransition)
{
  for (ListTransition::const_iterator i = listtransition->begin() ; i != listtransition->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtransition->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitGuard(Guard *p) {} //abstract class

void ShowAbsyn::visitGuardSquares(GuardSquares *p)
{
  bufAppend('(');
  bufAppend("GuardSquares");
  bufAppend(' ');
  bufAppend('[');
  if (p->listseqelt_)  p->listseqelt_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitGuardWithPreEmpty(GuardWithPreEmpty *p)
{
  bufAppend('(');
  bufAppend("GuardWithPreEmpty");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->precond_)  p->precond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->postcond_)  p->postcond_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitGuardWithPre(GuardWithPre *p)
{
  bufAppend('(');
  bufAppend("GuardWithPre");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->precond_)  p->precond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listseqelt_)  p->listseqelt_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->postcond_)  p->postcond_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitGuardPostOnly(GuardPostOnly *p)
{
  bufAppend('(');
  bufAppend("GuardPostOnly");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listseqelt_)  p->listseqelt_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->postcond_)  p->postcond_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitGuardPostOnlyEmpty(GuardPostOnlyEmpty *p)
{
  bufAppend('(');
  bufAppend("GuardPostOnlyEmpty");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->postcond_)  p->postcond_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPreCond(PreCond *p) {} //abstract class

void ShowAbsyn::visitPrecondCC(PrecondCC *p)
{
  bufAppend('(');
  bufAppend("PrecondCC");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitPrecondBB(PrecondBB *p)
{
  bufAppend('(');
  bufAppend("PrecondBB");
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitPostCond(PostCond *p) {} //abstract class

void ShowAbsyn::visitPostcondEmpty(PostcondEmpty *p)
{
  bufAppend("PostcondEmpty");
}
void ShowAbsyn::visitPostcondSimple(PostcondSimple *p)
{
  bufAppend('(');
  bufAppend("PostcondSimple");
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitSeqElt(SeqElt *p) {} //abstract class

void ShowAbsyn::visitSeqEltCond(SeqEltCond *p)
{
  bufAppend('(');
  bufAppend("SeqEltCond");
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitSeqEltGuardRep(SeqEltGuardRep *p)
{
  bufAppend('(');
  bufAppend("SeqEltGuardRep");
  bufAppend(' ');
  bufAppend('[');
  if (p->guard_)  p->guard_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->repetition_)  p->repetition_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListSeqElt(ListSeqElt *listseqelt)
{
  for (ListSeqElt::const_iterator i = listseqelt->begin() ; i != listseqelt->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listseqelt->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitRepetition(Repetition *p) {} //abstract class

void ShowAbsyn::visitRepetitionEmpty(RepetitionEmpty *p)
{
  bufAppend("RepetitionEmpty");
}
void ShowAbsyn::visitRepetitionPlus(RepetitionPlus *p)
{
  bufAppend("RepetitionPlus");
}
void ShowAbsyn::visitRepetitionMinus(RepetitionMinus *p)
{
  bufAppend("RepetitionMinus");
}
void ShowAbsyn::visitRepetitionQuestion(RepetitionQuestion *p)
{
  bufAppend("RepetitionQuestion");
}
void ShowAbsyn::visitRepetitionPair(RepetitionPair *p)
{
  bufAppend('(');
  bufAppend("RepetitionPair");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRepetitionOne(RepetitionOne *p)
{
  bufAppend('(');
  bufAppend("RepetitionOne");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRepetitionREmpty(RepetitionREmpty *p)
{
  bufAppend('(');
  bufAppend("RepetitionREmpty");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRepetitionLEmpty(RepetitionLEmpty *p)
{
  bufAppend('(');
  bufAppend("RepetitionLEmpty");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitCond(Cond *p) {} //abstract class

void ShowAbsyn::visitLogicOr(LogicOr *p)
{
  bufAppend('(');
  bufAppend("LogicOr");
  bufAppend(' ');
  p->cond_1->accept(this);
  bufAppend(' ');
  p->cond_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicAnd(LogicAnd *p)
{
  bufAppend('(');
  bufAppend("LogicAnd");
  bufAppend(' ');
  p->cond_1->accept(this);
  bufAppend(' ');
  p->cond_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitACondCOR(ACondCOR *p)
{
  bufAppend('(');
  bufAppend("ACondCOR");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitACondCALL(ACondCALL *p)
{
  bufAppend('(');
  bufAppend("ACondCALL");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitACondReturn(ACondReturn *p)
{
  bufAppend('(');
  bufAppend("ACondReturn");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitACondTrue(ACondTrue *p)
{
  bufAppend("ACondTrue");
}
void ShowAbsyn::visitACondFalse(ACondFalse *p)
{
  bufAppend("ACondFalse");
}
void ShowAbsyn::visitACondNot(ACondNot *p)
{
  bufAppend('(');
  bufAppend("ACondNot");
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRelationCond(RelationCond *p)
{
  bufAppend('(');
  bufAppend("RelationCond");
  bufAppend(' ');
  bufAppend('[');
  if (p->logicrelation_)  p->logicrelation_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitLogicRelation(LogicRelation *p) {} //abstract class

void ShowAbsyn::visitLogicEQ(LogicEQ *p)
{
  bufAppend('(');
  bufAppend("LogicEQ");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicLess(LogicLess *p)
{
  bufAppend('(');
  bufAppend("LogicLess");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicGreater(LogicGreater *p)
{
  bufAppend('(');
  bufAppend("LogicGreater");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicLessEQ(LogicLessEQ *p)
{
  bufAppend('(');
  bufAppend("LogicLessEQ");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicGreaterEQ(LogicGreaterEQ *p)
{
  bufAppend('(');
  bufAppend("LogicGreaterEQ");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicNotEQ(LogicNotEQ *p)
{
  bufAppend('(');
  bufAppend("LogicNotEQ");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitExpr(Expr *p) {} //abstract class

void ShowAbsyn::visitAdd(Add *p)
{
  bufAppend('(');
  bufAppend("Add");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitSubtract(Subtract *p)
{
  bufAppend('(');
  bufAppend("Subtract");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitDivide(Divide *p)
{
  bufAppend('(');
  bufAppend("Divide");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitMultiply(Multiply *p)
{
  bufAppend('(');
  bufAppend("Multiply");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitMod(Mod *p)
{
  bufAppend('(');
  bufAppend("Mod");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitBitAnd(BitAnd *p)
{
  bufAppend('(');
  bufAppend("BitAnd");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitBitOr(BitOr *p)
{
  bufAppend('(');
  bufAppend("BitOr");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitBitXor(BitXor *p)
{
  bufAppend('(');
  bufAppend("BitXor");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitInt(Int *p)
{
  bufAppend('(');
  bufAppend("Int");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitFloat(Float *p)
{
  bufAppend('(');
  bufAppend("Float");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitNegativeInt(NegativeInt *p)
{
  bufAppend('(');
  bufAppend("NegativeInt");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitNegativeDouble(NegativeDouble *p)
{
  bufAppend('(');
  bufAppend("NegativeDouble");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitStructFielsAccess(StructFielsAccess *p)
{
  bufAppend('(');
  bufAppend("StructFielsAccess");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitPointerAccess(PointerAccess *p)
{
  bufAppend('(');
  bufAppend("PointerAccess");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitArrayAccess(ArrayAccess *p)
{
  bufAppend('(');
  bufAppend("ArrayAccess");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRefAccess(RefAccess *p)
{
  bufAppend('(');
  bufAppend("RefAccess");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFunAccess(FunAccess *p)
{
  bufAppend('(');
  bufAppend("FunAccess");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(')');
}
void ShowAbsyn::visitIdentifier(Identifier *p)
{
  bufAppend('(');
  bufAppend("Identifier");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitMetavarAccess(MetavarAccess *p)
{
  bufAppend('(');
  bufAppend("MetavarAccess");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitAction(Action *p) {} //abstract class

void ShowAbsyn::visitAnAction(AnAction *p)
{
  bufAppend('(');
  bufAppend("AnAction");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListAction(ListAction *listaction)
{
  for (ListAction::const_iterator i = listaction->begin() ; i != listaction->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listaction->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


}
