-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for FullCAcsl.

module FullCAcsl.FullCAcslParser.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified FullCAcsl.FullCAcslParser.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print FullCAcsl.FullCAcslParser.Abs.Ident where
  prt _ (FullCAcsl.FullCAcslParser.Abs.Ident i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.SIGNED where
  prt _ (FullCAcsl.FullCAcslParser.Abs.SIGNED i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.LBRACE where
  prt _ (FullCAcsl.FullCAcslParser.Abs.LBRACE i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.RBRACE where
  prt _ (FullCAcsl.FullCAcslParser.Abs.RBRACE i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.CONST where
  prt _ (FullCAcsl.FullCAcslParser.Abs.CONST i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.RESTRICT where
  prt _ (FullCAcsl.FullCAcslParser.Abs.RESTRICT i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.VOLATILE where
  prt _ (FullCAcsl.FullCAcslParser.Abs.VOLATILE i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.BLOCKATTRIBUTE where
  prt _ (FullCAcsl.FullCAcslParser.Abs.BLOCKATTRIBUTE i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.LBRACKET where
  prt _ (FullCAcsl.FullCAcslParser.Abs.LBRACKET i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.RBRACKET where
  prt _ (FullCAcsl.FullCAcslParser.Abs.RBRACKET i) = doc $ showString i
instance Print FullCAcsl.FullCAcslParser.Abs.Program where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AProgram globals -> prPrec i 0 (concatD [prt 0 globals])

instance Print FullCAcsl.FullCAcslParser.Abs.Globals where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoGlobals -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SimpleGlobals global globals -> prPrec i 0 (concatD [prt 0 global, prt 0 globals])
    FullCAcsl.FullCAcslParser.Abs.SemiColonGlobals globals -> prPrec i 0 (concatD [doc (showString ";"), prt 0 globals])

instance Print FullCAcsl.FullCAcslParser.Abs.Global where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.GlobalsFunctionDef functiondef -> prPrec i 0 (concatD [prt 0 functiondef])
    FullCAcsl.FullCAcslParser.Abs.GlobalsDeclataion declaration -> prPrec i 0 (concatD [prt 0 declaration])

instance Print FullCAcsl.FullCAcslParser.Abs.FunctionDef where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleFunctionDef functiondefstart block -> prPrec i 0 (concatD [prt 0 functiondefstart, prt 0 block])
    FullCAcsl.FullCAcslParser.Abs.FunctionDefSpec acslprogram functiondefstart block -> prPrec i 0 (concatD [prt 0 acslprogram, prt 0 functiondefstart, prt 0 block])

instance Print FullCAcsl.FullCAcslParser.Abs.FunctionDefStart where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.FunctionDefStartDeclarator declspeclist declarator -> prPrec i 0 (concatD [prt 0 declspeclist, prt 0 declarator])

instance Print FullCAcsl.FullCAcslParser.Abs.DeclSpecList where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.DeclSpecTypeSpec typespec -> prPrec i 0 (concatD [prt 0 typespec])
    FullCAcsl.FullCAcslParser.Abs.DeclSpecTypeSpecNext typespec declspeclistnonamed -> prPrec i 0 (concatD [prt 0 typespec, prt 0 declspeclistnonamed])

instance Print FullCAcsl.FullCAcslParser.Abs.DeclSpecListNoNamed where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.DeclSpecNoNamedTypeSpec typespec -> prPrec i 0 (concatD [prt 0 typespec])
    FullCAcsl.FullCAcslParser.Abs.DeclSpecNoNamedTypeSpecNext typespec declspeclistnonamed -> prPrec i 0 (concatD [prt 0 typespec, prt 0 declspeclistnonamed])

instance Print FullCAcsl.FullCAcslParser.Abs.TypeSpec where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.TypeSpecVoidKeyWord -> prPrec i 0 (concatD [doc (showString "void")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecCharKeyWord -> prPrec i 0 (concatD [doc (showString "char")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecBoolKeyWord -> prPrec i 0 (concatD [doc (showString "_Bool")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecShortKeyWord -> prPrec i 0 (concatD [doc (showString "short")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecInt32KeyWord -> prPrec i 0 (concatD [doc (showString "__int32")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecIntKeyWord -> prPrec i 0 (concatD [doc (showString "int")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSizeTKeyWord -> prPrec i 0 (concatD [doc (showString "size_t")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecLongKeyWord -> prPrec i 0 (concatD [doc (showString "long")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecInt64KeyWord -> prPrec i 0 (concatD [doc (showString "__int64")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecFloatKeyWord -> prPrec i 0 (concatD [doc (showString "float")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecDoubleKeyWord -> prPrec i 0 (concatD [doc (showString "double")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSignedKeyWord signed -> prPrec i 0 (concatD [prt 0 signed])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecUnsignedKeyWord -> prPrec i 0 (concatD [doc (showString "unsigned")])
    FullCAcsl.FullCAcslParser.Abs.StructId idortypename -> prPrec i 0 (concatD [doc (showString "struct"), prt 0 idortypename])
    FullCAcsl.FullCAcslParser.Abs.StructIdBraces idortypename structdecllist -> prPrec i 0 (concatD [doc (showString "struct"), prt 0 idortypename, doc (showString "{"), prt 0 structdecllist, doc (showString "}")])
    FullCAcsl.FullCAcslParser.Abs.StructBraces structdecllist -> prPrec i 0 (concatD [doc (showString "struct"), doc (showString "{"), prt 0 structdecllist, doc (showString "}")])

instance Print FullCAcsl.FullCAcslParser.Abs.Declarator where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ADeclarator pointeropt directdecl attributeswithasm -> prPrec i 0 (concatD [prt 0 pointeropt, prt 0 directdecl, prt 0 attributeswithasm])

instance Print FullCAcsl.FullCAcslParser.Abs.PointerOpt where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoPointer -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomePointer attributes pointeropt -> prPrec i 0 (concatD [doc (showString "*"), prt 0 attributes, prt 0 pointeropt])

instance Print FullCAcsl.FullCAcslParser.Abs.DirectDecl where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.DirectDeclIdTypename idortypename -> prPrec i 0 (concatD [prt 0 idortypename])
    FullCAcsl.FullCAcslParser.Abs.DirectDeclGhostParam directdecl ghostparameteropt -> prPrec i 0 (concatD [prt 0 directdecl, doc (showString "("), doc (showString ")"), prt 0 ghostparameteropt])
    FullCAcsl.FullCAcslParser.Abs.DirectDeclGhostRestParParam directdecl restparlist ghostparameteropt -> prPrec i 0 (concatD [prt 0 directdecl, doc (showString "("), prt 0 restparlist, doc (showString ")"), prt 0 ghostparameteropt])

instance Print FullCAcsl.FullCAcslParser.Abs.AttributesWithAsm where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.EmptyAttrWithASM -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.RestParList where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleParameterDecl parameterdecls -> prPrec i 0 (concatD [prt 0 parameterdecls])

instance Print FullCAcsl.FullCAcslParser.Abs.ParameterDecl where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ParameterDeclSpecDeclarator declspeclist declarator -> prPrec i 0 (concatD [prt 0 declspeclist, prt 0 declarator])
    FullCAcsl.FullCAcslParser.Abs.ParameterDeclSpec declspeclist -> prPrec i 0 (concatD [prt 0 declspeclist])
    FullCAcsl.FullCAcslParser.Abs.ParameterDeclPar parameterdecl -> prPrec i 0 (concatD [doc (showString "("), prt 0 parameterdecl, doc (showString ")")])

instance Print [FullCAcsl.FullCAcslParser.Abs.ParameterDecl] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.GhostParameterOpt where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoGhostParameter -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.IdOrTypename where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.IdTypename idortypenameasid -> prPrec i 0 (concatD [prt 0 idortypenameasid])

instance Print FullCAcsl.FullCAcslParser.Abs.IdOrTypenameAsId where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.IdOrTypenameAsIdIdentifier id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print FullCAcsl.FullCAcslParser.Abs.Declaration where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.DeclSpecInitDecl declspeclist declandinitdeclattrlist -> prPrec i 0 (concatD [prt 0 declspeclist, prt 0 declandinitdeclattrlist, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.DeclSpec declspeclist -> prPrec i 0 (concatD [prt 0 declspeclist, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.SpecDeclSpecInitDecl acslprogram declspeclist declandinitdeclattrlist -> prPrec i 0 (concatD [prt 0 acslprogram, prt 0 declspeclist, prt 0 declandinitdeclattrlist, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.SpecDeclSpec acslprogram declspeclist -> prPrec i 0 (concatD [prt 0 acslprogram, prt 0 declspeclist, doc (showString ";")])

instance Print FullCAcsl.FullCAcslParser.Abs.DeclAndInitDeclAttrList where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.InitDeclaration initdeclarator -> prPrec i 0 (concatD [prt 0 initdeclarator])
    FullCAcsl.FullCAcslParser.Abs.InitDeclarationWithAttr initdeclarator initdeclaratorattrs -> prPrec i 0 (concatD [prt 0 initdeclarator, doc (showString ","), prt 0 initdeclaratorattrs])

instance Print FullCAcsl.FullCAcslParser.Abs.InitDeclaratorAttr where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.InitDeclaratorAttribute initdeclarator -> prPrec i 0 (concatD [prt 0 initdeclarator])

instance Print [FullCAcsl.FullCAcslParser.Abs.InitDeclaratorAttr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.InitDeclarator where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleInitDeclarator declarator -> prPrec i 0 (concatD [prt 0 declarator])

instance Print FullCAcsl.FullCAcslParser.Abs.StructDeclList where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.EmptyStructDecl -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.DeclSpecStructDecl declspeclist structdecllist -> prPrec i 0 (concatD [prt 0 declspeclist, doc (showString ";"), prt 0 structdecllist])
    FullCAcsl.FullCAcslParser.Abs.SemicolonStructDecl structdecllist -> prPrec i 0 (concatD [doc (showString ";"), prt 0 structdecllist])
    FullCAcsl.FullCAcslParser.Abs.SpecFieldDeclStructDecl declspeclist fielddecls structdecllist -> prPrec i 0 (concatD [prt 0 declspeclist, prt 0 fielddecls, doc (showString ";"), prt 0 structdecllist])

instance Print FullCAcsl.FullCAcslParser.Abs.FieldDecl where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.FieldDeclDeclarator declarator -> prPrec i 0 (concatD [prt 0 declarator])

instance Print [FullCAcsl.FullCAcslParser.Abs.FieldDecl] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.Attribute where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AttributeConst const -> prPrec i 0 (concatD [prt 0 const])

instance Print [FullCAcsl.FullCAcslParser.Abs.Attribute] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.Block where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ABlock blockattrs blockelements -> prPrec i 0 (concatD [doc (showString "{"), prt 0 blockattrs, prt 0 blockelements, doc (showString "}")])

instance Print FullCAcsl.FullCAcslParser.Abs.BlockAttrs where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoBlockAttrs -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomeBlockAttrs blockattribute attrs -> prPrec i 0 (concatD [prt 0 blockattribute, doc (showString "("), prt 0 attrs, doc (showString ")")])

instance Print FullCAcsl.FullCAcslParser.Abs.BlockElement where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.DeclarationElement declaration -> prPrec i 0 (concatD [prt 0 declaration])
    FullCAcsl.FullCAcslParser.Abs.StatementElement statement -> prPrec i 0 (concatD [prt 0 statement])

instance Print [FullCAcsl.FullCAcslParser.Abs.BlockElement] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.Statement where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SemicolonStatement -> prPrec i 0 (concatD [doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.SpecStatement acslprogram annotatedstmt -> prPrec i 0 (concatD [prt 0 acslprogram, prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.ExprsStatement expressions -> prPrec i 0 (concatD [prt 0 expressions, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.BlockStatement block -> prPrec i 0 (concatD [prt 0 block])
    FullCAcsl.FullCAcslParser.Abs.IfStatement expressions annotatedstmt elsepart -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expressions, doc (showString ")"), prt 0 annotatedstmt, prt 0 elsepart])
    FullCAcsl.FullCAcslParser.Abs.SwitchStatement expressions annotatedstmt -> prPrec i 0 (concatD [doc (showString "switch"), doc (showString "("), prt 0 expressions, doc (showString ")"), prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.WhileStatement expressions annotatedstmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expressions, doc (showString ")"), prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.ForStatement forclause optexpression1 optexpression2 annotatedstmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 forclause, prt 0 optexpression1, doc (showString ";"), prt 0 optexpression2, doc (showString ")"), prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.CaseStatement expression annotatedstmt -> prPrec i 0 (concatD [doc (showString "case"), prt 0 expression, doc (showString ":"), prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.CaseSliceStatement expression1 expression2 annotatedstmt -> prPrec i 0 (concatD [doc (showString "case"), prt 0 expression1, doc (showString "..."), prt 0 expression2, doc (showString ":"), prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.DefaultStatement annotatedstmt -> prPrec i 0 (concatD [doc (showString "default"), doc (showString ":"), prt 0 annotatedstmt])
    FullCAcsl.FullCAcslParser.Abs.EmptyReturnStatement -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.ReturnStatement expressions -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expressions, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.BreakStatement -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.ContinueStatement -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])

instance Print FullCAcsl.FullCAcslParser.Abs.ForClause where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ForClauseExpression optexpression -> prPrec i 0 (concatD [prt 0 optexpression, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.ForClauseDeclaration declaration -> prPrec i 0 (concatD [prt 0 declaration])

instance Print FullCAcsl.FullCAcslParser.Abs.Attr where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AnAttr attr1 attr2 -> prPrec i 0 (concatD [prt 1 attr1, doc (showString "="), prt 1 attr2])
    FullCAcsl.FullCAcslParser.Abs.TernaryCond attr1 attr2 attr3 -> prPrec i 1 (concatD [prt 2 attr1, doc (showString "?"), prt 1 attr2, doc (showString ":"), prt 1 attr3])
    FullCAcsl.FullCAcslParser.Abs.Or attr1 attr2 -> prPrec i 2 (concatD [prt 2 attr1, doc (showString "||"), prt 3 attr2])
    FullCAcsl.FullCAcslParser.Abs.And attr1 attr2 -> prPrec i 3 (concatD [prt 3 attr1, doc (showString "&&"), prt 4 attr2])
    FullCAcsl.FullCAcslParser.Abs.BitOr attr1 attr2 -> prPrec i 4 (concatD [prt 4 attr1, doc (showString "|"), prt 5 attr2])
    FullCAcsl.FullCAcslParser.Abs.Xor attr1 attr2 -> prPrec i 5 (concatD [prt 5 attr1, doc (showString "^"), prt 6 attr2])
    FullCAcsl.FullCAcslParser.Abs.BitAnd attr1 attr2 -> prPrec i 6 (concatD [prt 6 attr1, doc (showString "&"), prt 7 attr2])
    FullCAcsl.FullCAcslParser.Abs.EqualEqual attr1 attr2 -> prPrec i 7 (concatD [prt 7 attr1, doc (showString "=="), prt 8 attr2])
    FullCAcsl.FullCAcslParser.Abs.NotEqual attr1 attr2 -> prPrec i 7 (concatD [prt 7 attr1, doc (showString "!="), prt 8 attr2])
    FullCAcsl.FullCAcslParser.Abs.Less attr1 attr2 -> prPrec i 8 (concatD [prt 8 attr1, doc (showString "<"), prt 9 attr2])
    FullCAcsl.FullCAcslParser.Abs.Greater attr1 attr2 -> prPrec i 8 (concatD [prt 8 attr1, doc (showString ">"), prt 9 attr2])
    FullCAcsl.FullCAcslParser.Abs.LessEqual attr1 attr2 -> prPrec i 8 (concatD [prt 8 attr1, doc (showString "<="), prt 9 attr2])
    FullCAcsl.FullCAcslParser.Abs.GreaterEqual attr1 attr2 -> prPrec i 8 (concatD [prt 8 attr1, doc (showString ">="), prt 9 attr2])
    FullCAcsl.FullCAcslParser.Abs.LeftShiftOp attr1 attr2 -> prPrec i 9 (concatD [prt 9 attr1, doc (showString "<<"), prt 10 attr2])
    FullCAcsl.FullCAcslParser.Abs.RightShiftOp attr1 attr2 -> prPrec i 9 (concatD [prt 9 attr1, doc (showString ">>"), prt 10 attr2])
    FullCAcsl.FullCAcslParser.Abs.AddOp attr1 attr2 -> prPrec i 10 (concatD [prt 10 attr1, doc (showString "+"), prt 11 attr2])
    FullCAcsl.FullCAcslParser.Abs.SubOp attr1 attr2 -> prPrec i 10 (concatD [prt 10 attr1, doc (showString "-"), prt 11 attr2])
    FullCAcsl.FullCAcslParser.Abs.MultOp attr1 attr2 -> prPrec i 11 (concatD [prt 11 attr1, doc (showString "*"), prt 12 attr2])
    FullCAcsl.FullCAcslParser.Abs.DivOp attr1 attr2 -> prPrec i 11 (concatD [prt 11 attr1, doc (showString "/"), prt 12 attr2])
    FullCAcsl.FullCAcslParser.Abs.ModOp attr1 attr2 -> prPrec i 11 (concatD [prt 11 attr1, doc (showString "%"), prt 12 attr2])
    FullCAcsl.FullCAcslParser.Abs.PlusUnaryAttr attr -> prPrec i 12 (concatD [doc (showString "+"), prt 12 attr])
    FullCAcsl.FullCAcslParser.Abs.MinusUnaryAttr attr -> prPrec i 12 (concatD [doc (showString "-"), prt 12 attr])
    FullCAcsl.FullCAcslParser.Abs.MultUnaryAttr attr -> prPrec i 12 (concatD [doc (showString "*"), prt 12 attr])
    FullCAcsl.FullCAcslParser.Abs.AmpUnaryAttr attr -> prPrec i 12 (concatD [doc (showString "&"), prt 12 attr])
    FullCAcsl.FullCAcslParser.Abs.NotUnaryAttr attr -> prPrec i 12 (concatD [doc (showString "!"), prt 12 attr])
    FullCAcsl.FullCAcslParser.Abs.TildeUnaryAttr attr -> prPrec i 12 (concatD [doc (showString "~"), prt 12 attr])
    FullCAcsl.FullCAcslParser.Abs.FuncationCall idortypenameasid attrs -> prPrec i 13 (concatD [prt 0 idortypenameasid, doc (showString "("), prt 0 attrs, doc (showString ")")])
    FullCAcsl.FullCAcslParser.Abs.ProcedureCall idortypenameasid -> prPrec i 13 (concatD [prt 0 idortypenameasid, doc (showString "("), doc (showString ")")])
    FullCAcsl.FullCAcslParser.Abs.ArrowAttr attr idortypename -> prPrec i 13 (concatD [prt 13 attr, doc (showString "->"), prt 0 idortypename])
    FullCAcsl.FullCAcslParser.Abs.DotAttr attr idortypename -> prPrec i 13 (concatD [prt 13 attr, doc (showString "."), prt 0 idortypename])
    FullCAcsl.FullCAcslParser.Abs.ArrayAttr attr1 attr2 -> prPrec i 13 (concatD [prt 13 attr1, doc (showString "["), prt 0 attr2, doc (showString "]")])
    FullCAcsl.FullCAcslParser.Abs.BasicAttr basicattribute -> prPrec i 14 (concatD [prt 0 basicattribute])

instance Print [FullCAcsl.FullCAcslParser.Abs.Attr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.BasicAttribute where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.BasicAttrConsInt n -> prPrec i 0 (concatD [prt 0 n])
    FullCAcsl.FullCAcslParser.Abs.BasicAttrConsFloat d -> prPrec i 0 (concatD [prt 0 d])

instance Print FullCAcsl.FullCAcslParser.Abs.AnnotatedStmt where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AnnotatedStatement statement -> prPrec i 0 (concatD [prt 0 statement])

instance Print FullCAcsl.FullCAcslParser.Abs.ElsePart where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoElsePart -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SimpleElsePart annotatedstmt -> prPrec i 0 (concatD [doc (showString "else"), prt 0 annotatedstmt])

instance Print FullCAcsl.FullCAcslParser.Abs.OptExpression where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoExpression -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomeExpression expressions -> prPrec i 0 (concatD [prt 0 expressions])

instance Print FullCAcsl.FullCAcslParser.Abs.Expression where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AssignmentExpr assignexpr -> prPrec i 0 (concatD [prt 0 assignexpr])

instance Print [FullCAcsl.FullCAcslParser.Abs.Expression] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.AssignExpr where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.EqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.PlusEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "+="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.MinusEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "-="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.MultEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "*="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.DivEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "/="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.ModEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "%="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.AndEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "&="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.OrEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "|="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.XorEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "^="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.LeftShiftEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString "<<="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.RightShiftEqAssignExpr assignexpr1 assignexpr2 -> prPrec i 0 (concatD [prt 12 assignexpr1, doc (showString ">>="), prt 0 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.TernaryCondExpr assignexpr1 optexpression assignexpr2 -> prPrec i 1 (concatD [prt 2 assignexpr1, doc (showString "?"), prt 0 optexpression, doc (showString ":"), prt 1 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.OrExpr assignexpr1 assignexpr2 -> prPrec i 2 (concatD [prt 2 assignexpr1, doc (showString "||"), prt 3 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.AndExpr assignexpr1 assignexpr2 -> prPrec i 3 (concatD [prt 3 assignexpr1, doc (showString "&&"), prt 4 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.BitOrExpr assignexpr1 assignexpr2 -> prPrec i 4 (concatD [prt 4 assignexpr1, doc (showString "|"), prt 5 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.BitXorExpr assignexpr1 assignexpr2 -> prPrec i 5 (concatD [prt 5 assignexpr1, doc (showString "^"), prt 6 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.BitAndExpr assignexpr1 assignexpr2 -> prPrec i 6 (concatD [prt 6 assignexpr1, doc (showString "&"), prt 7 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.EqExpr assignexpr1 assignexpr2 -> prPrec i 7 (concatD [prt 7 assignexpr1, doc (showString "=="), prt 8 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.NotEqExpr assignexpr1 assignexpr2 -> prPrec i 7 (concatD [prt 7 assignexpr1, doc (showString "!="), prt 8 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.LessExpr assignexpr1 assignexpr2 -> prPrec i 8 (concatD [prt 8 assignexpr1, doc (showString "<"), prt 9 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.GreaterExpr assignexpr1 assignexpr2 -> prPrec i 8 (concatD [prt 8 assignexpr1, doc (showString ">"), prt 9 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.LessEqualExpr assignexpr1 assignexpr2 -> prPrec i 8 (concatD [prt 8 assignexpr1, doc (showString "<="), prt 9 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.GreaterEqualExpr assignexpr1 assignexpr2 -> prPrec i 8 (concatD [prt 8 assignexpr1, doc (showString ">="), prt 9 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.LeftShiftExpr assignexpr1 assignexpr2 -> prPrec i 9 (concatD [prt 9 assignexpr1, doc (showString "<<"), prt 10 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.RightShiftExpr assignexpr1 assignexpr2 -> prPrec i 9 (concatD [prt 9 assignexpr1, doc (showString ">>"), prt 10 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.PlusExpr assignexpr1 assignexpr2 -> prPrec i 10 (concatD [prt 10 assignexpr1, doc (showString "+"), prt 11 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.MinusExpr assignexpr1 assignexpr2 -> prPrec i 10 (concatD [prt 10 assignexpr1, doc (showString "-"), prt 11 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.MulsExpr assignexpr1 assignexpr2 -> prPrec i 11 (concatD [prt 11 assignexpr1, doc (showString "*"), prt 12 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.DivExpr assignexpr1 assignexpr2 -> prPrec i 11 (concatD [prt 11 assignexpr1, doc (showString "/"), prt 12 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.ModExpr assignexpr1 assignexpr2 -> prPrec i 11 (concatD [prt 11 assignexpr1, doc (showString "%"), prt 12 assignexpr2])
    FullCAcsl.FullCAcslParser.Abs.CastExpr typename assignexpr -> prPrec i 12 (concatD [doc (showString "("), prt 0 typename, doc (showString ")"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprPlusPlus assignexpr -> prPrec i 13 (concatD [doc (showString "++"), prt 13 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprMinusMinus assignexpr -> prPrec i 13 (concatD [doc (showString "--"), prt 13 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprPlus assignexpr -> prPrec i 13 (concatD [doc (showString "+"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprMinus assignexpr -> prPrec i 13 (concatD [doc (showString "-"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprMult assignexpr -> prPrec i 13 (concatD [doc (showString "*"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprAmp assignexpr -> prPrec i 13 (concatD [doc (showString "&"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprNot assignexpr -> prPrec i 13 (concatD [doc (showString "!"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprTilde assignexpr -> prPrec i 13 (concatD [doc (showString "~"), prt 12 assignexpr])
    FullCAcsl.FullCAcslParser.Abs.UnaryExprAddress idortypenameasid -> prPrec i 13 (concatD [doc (showString "&&"), prt 0 idortypenameasid])
    FullCAcsl.FullCAcslParser.Abs.BracketsPostfixExpression assignexpr expressions -> prPrec i 14 (concatD [prt 14 assignexpr, doc (showString "["), prt 0 expressions, doc (showString "]")])
    FullCAcsl.FullCAcslParser.Abs.DotPostfixExpression assignexpr idortypename -> prPrec i 14 (concatD [prt 14 assignexpr, doc (showString "."), prt 0 idortypename])
    FullCAcsl.FullCAcslParser.Abs.ArrowPostfixExpression assignexpr idortypename -> prPrec i 14 (concatD [prt 14 assignexpr, doc (showString "->"), prt 0 idortypename])
    FullCAcsl.FullCAcslParser.Abs.PlusPlusPostfixExpression assignexpr -> prPrec i 14 (concatD [prt 14 assignexpr, doc (showString "++")])
    FullCAcsl.FullCAcslParser.Abs.MinusMinusPostfixExpression assignexpr -> prPrec i 14 (concatD [prt 14 assignexpr, doc (showString "--")])
    FullCAcsl.FullCAcslParser.Abs.IdentifierPrimaryExpression id_ -> prPrec i 15 (concatD [prt 0 id_])
    FullCAcsl.FullCAcslParser.Abs.ConstantPrimaryExpressin constant -> prPrec i 15 (concatD [prt 0 constant])
    FullCAcsl.FullCAcslParser.Abs.CommaExpressionPrimaryExpressin expressions -> prPrec i 15 (concatD [doc (showString "("), prt 0 expressions, doc (showString ")")])
    FullCAcsl.FullCAcslParser.Abs.BlockPrimaryExpressin block -> prPrec i 15 (concatD [doc (showString "("), prt 0 block, doc (showString ")")])

instance Print FullCAcsl.FullCAcslParser.Abs.Constant where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ConstantInt n -> prPrec i 0 (concatD [prt 0 n])
    FullCAcsl.FullCAcslParser.Abs.ConstantFloat d -> prPrec i 0 (concatD [prt 0 d])
    FullCAcsl.FullCAcslParser.Abs.ConstantChar c -> prPrec i 0 (concatD [prt 0 c])

instance Print FullCAcsl.FullCAcslParser.Abs.TypeName where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.TypeNameDeclSpecList declspeclist -> prPrec i 0 (concatD [prt 0 declspeclist])

instance Print FullCAcsl.FullCAcslParser.Abs.ACSLProgram where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AnnotProgram annot -> prPrec i 0 (concatD [doc (showString "ACSL_START"), prt 0 annot, doc (showString "ACSL_END")])
    FullCAcsl.FullCAcslParser.Abs.AnnotationProgram logicptreeannot -> prPrec i 0 (concatD [doc (showString "ACSL_START"), prt 0 logicptreeannot, doc (showString "ACSL_END")])

instance Print FullCAcsl.FullCAcslParser.Abs.Annot where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.CodeAnnot codeannot -> prPrec i 0 (concatD [prt 0 codeannot])

instance Print FullCAcsl.FullCAcslParser.Abs.Code_Annot where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.CodeAnnotContract contract -> prPrec i 0 (concatD [prt 0 contract])

instance Print FullCAcsl.FullCAcslParser.Abs.Contract where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleContract requires terminates decreases simpleclauses behaviors completeordisjoint -> prPrec i 0 (concatD [prt 0 requires, prt 0 terminates, prt 0 decreases, prt 0 simpleclauses, prt 0 behaviors, prt 0 completeordisjoint])

instance Print FullCAcsl.FullCAcslParser.Abs.Requires where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoRequires -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomeRequires nerequires -> prPrec i 0 (concatD [prt 0 nerequires])

instance Print FullCAcsl.FullCAcslParser.Abs.NERequires where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleRequires lexpr requires -> prPrec i 0 (concatD [doc (showString "requires"), prt 0 lexpr, doc (showString ";"), prt 0 requires])
    FullCAcsl.FullCAcslParser.Abs.CheckRequires lexpr requires -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "requires"), prt 0 lexpr, doc (showString ";"), prt 0 requires])
    FullCAcsl.FullCAcslParser.Abs.AdimtRequires lexpr requires -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "requires"), prt 0 lexpr, doc (showString ";"), prt 0 requires])

instance Print FullCAcsl.FullCAcslParser.Abs.Terminates where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoTerminate -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.Decreases where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoDecreases -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.SimpleClauses where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoSimpleClauses -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomeSimpleClauses nesimpleclauses -> prPrec i 0 (concatD [prt 0 nesimpleclauses])

instance Print FullCAcsl.FullCAcslParser.Abs.NESimpleClauses where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.PostCondSimpleClauses postcond lexpr simpleclauses -> prPrec i 0 (concatD [prt 0 postcond, prt 0 lexpr, doc (showString ";"), prt 0 simpleclauses])
    FullCAcsl.FullCAcslParser.Abs.AssignsSimpleClauses assigns simpleclauses -> prPrec i 0 (concatD [doc (showString "assigns"), prt 0 assigns, doc (showString ";"), prt 0 simpleclauses])

instance Print FullCAcsl.FullCAcslParser.Abs.Assigns where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AssignZone zones -> prPrec i 0 (concatD [prt 0 zones])
    FullCAcsl.FullCAcslParser.Abs.AssignZoneFromZone lexprs zones -> prPrec i 0 (concatD [prt 0 lexprs, doc (showString "\\from"), prt 0 zones])

instance Print FullCAcsl.FullCAcslParser.Abs.Zones where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SomeZone lexprs -> prPrec i 0 (concatD [prt 0 lexprs])
    FullCAcsl.FullCAcslParser.Abs.NoZone -> prPrec i 0 (concatD [doc (showString "\\nothing")])

instance Print FullCAcsl.FullCAcslParser.Abs.Behaviors where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoBehaviors -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.CompleteOrDisjoint where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoComplDisj -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.Lexpr where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ImplLexpr lexpr1 lexpr2 -> prPrec i 0 (concatD [prt 0 lexpr1, doc (showString "==>"), prt 1 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.IffLexpr lexpr1 lexpr2 -> prPrec i 0 (concatD [prt 0 lexpr1, doc (showString "<==>"), prt 1 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.OrLexpr lexpr1 lexpr2 -> prPrec i 0 (concatD [prt 0 lexpr1, doc (showString "||"), prt 1 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.AndLexpr lexpr1 lexpr2 -> prPrec i 0 (concatD [prt 0 lexpr1, doc (showString "&&"), prt 1 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.HatHatLexpr lexpr1 lexpr2 -> prPrec i 0 (concatD [prt 0 lexpr1, doc (showString "^^"), prt 1 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.RelationLexpr lexpr1 lexprrelinners relation lexpr2 -> prPrec i 1 (concatD [prt 3 lexpr1, prt 0 lexprrelinners, prt 0 relation, prt 2 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.BinderLexpr lexprbinder -> prPrec i 2 (concatD [prt 0 lexprbinder])
    FullCAcsl.FullCAcslParser.Abs.NotBinderLexpr lexprbinder -> prPrec i 2 (concatD [doc (showString "!"), prt 0 lexprbinder])
    FullCAcsl.FullCAcslParser.Abs.TrueLexpr -> prPrec i 3 (concatD [doc (showString "\\true")])
    FullCAcsl.FullCAcslParser.Abs.FalseLexpr -> prPrec i 3 (concatD [doc (showString "\\false")])
    FullCAcsl.FullCAcslParser.Abs.ValidLexpr optlabel lexpr -> prPrec i 3 (concatD [doc (showString "\\valid"), prt 1 optlabel, doc (showString "("), prt 0 lexpr, doc (showString ")")])
    FullCAcsl.FullCAcslParser.Abs.AutomaticLexpr -> prPrec i 3 (concatD [doc (showString "\\automatic")])
    FullCAcsl.FullCAcslParser.Abs.DynamicLexpr -> prPrec i 3 (concatD [doc (showString "\\dynamic")])
    FullCAcsl.FullCAcslParser.Abs.RegisterLexpr -> prPrec i 3 (concatD [doc (showString "\\register")])
    FullCAcsl.FullCAcslParser.Abs.StaticLexpr -> prPrec i 3 (concatD [doc (showString "\\static")])
    FullCAcsl.FullCAcslParser.Abs.UnallocatedLexpr -> prPrec i 3 (concatD [doc (showString "\\unallocated")])
    FullCAcsl.FullCAcslParser.Abs.NullLexpr -> prPrec i 3 (concatD [doc (showString "\\null")])
    FullCAcsl.FullCAcslParser.Abs.LexprIntConst n -> prPrec i 3 (concatD [prt 0 n])
    FullCAcsl.FullCAcslParser.Abs.LexprFloatConst d -> prPrec i 3 (concatD [prt 0 d])
    FullCAcsl.FullCAcslParser.Abs.LexprStringConst str -> prPrec i 3 (concatD [printString str])
    FullCAcsl.FullCAcslParser.Abs.AddLexpr lexpr1 lexpr2 -> prPrec i 3 (concatD [prt 3 lexpr1, doc (showString "+"), prt 3 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.SubtrLexpr lexpr1 lexpr2 -> prPrec i 3 (concatD [prt 3 lexpr1, doc (showString "-"), prt 3 lexpr2])
    FullCAcsl.FullCAcslParser.Abs.SquaresRangeLexpr lexpr range -> prPrec i 3 (concatD [prt 3 lexpr, doc (showString "["), prt 0 range, doc (showString "]")])
    FullCAcsl.FullCAcslParser.Abs.SquaresLexpr lexpr1 lexpr2 -> prPrec i 3 (concatD [prt 3 lexpr1, doc (showString "["), prt 0 lexpr2, doc (showString "]")])
    FullCAcsl.FullCAcslParser.Abs.SeparatedLexpr lexprs -> prPrec i 3 (concatD [doc (showString "\\separated"), doc (showString "("), prt 0 lexprs, doc (showString ")")])
    FullCAcsl.FullCAcslParser.Abs.FullIdParenLexpr fullidentifier lexprs -> prPrec i 3 (concatD [prt 0 fullidentifier, doc (showString "("), prt 0 lexprs, doc (showString ")")])
    FullCAcsl.FullCAcslParser.Abs.FullId fullidentifier -> prPrec i 3 (concatD [prt 0 fullidentifier])
    FullCAcsl.FullCAcslParser.Abs.PiLexpr -> prPrec i 3 (concatD [doc (showString "\\pi")])
    FullCAcsl.FullCAcslParser.Abs.ParenRangeLexpr range -> prPrec i 3 (concatD [doc (showString "("), prt 0 range, doc (showString ")")])

instance Print [FullCAcsl.FullCAcslParser.Abs.Lexpr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.LexprRelInner where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.RelInnerLexpr relation lexpr -> prPrec i 0 (concatD [prt 0 relation, prt 3 lexpr])

instance Print [FullCAcsl.FullCAcslParser.Abs.LexprRelInner] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.Relation where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.LessRel -> prPrec i 0 (concatD [doc (showString "<")])
    FullCAcsl.FullCAcslParser.Abs.GreaterRel -> prPrec i 0 (concatD [doc (showString ">")])
    FullCAcsl.FullCAcslParser.Abs.LessEqRel -> prPrec i 0 (concatD [doc (showString "<=")])
    FullCAcsl.FullCAcslParser.Abs.GreaterEqRel -> prPrec i 0 (concatD [doc (showString ">=")])
    FullCAcsl.FullCAcslParser.Abs.EqRel -> prPrec i 0 (concatD [doc (showString "==")])
    FullCAcsl.FullCAcslParser.Abs.NotEqRel -> prPrec i 0 (concatD [doc (showString "!=")])

instance Print FullCAcsl.FullCAcslParser.Abs.LexprBinder where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ForallBinderLexpr binders lexpr -> prPrec i 0 (concatD [doc (showString "\\forall"), prt 0 binders, doc (showString ";"), prt 0 lexpr])
    FullCAcsl.FullCAcslParser.Abs.ExistBinderLexpr binders lexpr -> prPrec i 0 (concatD [doc (showString "\\exists"), prt 0 binders, doc (showString ";"), prt 0 lexpr])
    FullCAcsl.FullCAcslParser.Abs.LambdaBinderLexpr binders lexpr -> prPrec i 0 (concatD [doc (showString "\\lambda"), prt 0 binders, doc (showString ";"), prt 0 lexpr])

instance Print FullCAcsl.FullCAcslParser.Abs.Binders where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.TheBinders typespecoftypename varspec bindersreentrances -> prPrec i 0 (concatD [prt 0 typespecoftypename, prt 0 varspec, prt 0 bindersreentrances])

instance Print FullCAcsl.FullCAcslParser.Abs.TypeSpecOFTYPENAME where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.TypeSpecTYPENAME id_ -> prPrec i 0 (concatD [prt 0 id_])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleFromTypenameTypeSpec typespecsimple -> prPrec i 0 (concatD [prt 0 typespecsimple])

instance Print FullCAcsl.FullCAcslParser.Abs.BindersReentrance where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.BindersReentranceDeclSpec typespecoftypename varspec -> prPrec i 0 (concatD [doc (showString ","), prt 0 typespecoftypename, prt 0 varspec])
    FullCAcsl.FullCAcslParser.Abs.BindersReentranceVarSpec varspec -> prPrec i 0 (concatD [doc (showString ","), prt 0 varspec])

instance Print [FullCAcsl.FullCAcslParser.Abs.BindersReentrance] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.VarSpec where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.StartVarSpec starss varspec -> prPrec i 0 (concatD [prt 0 starss, prt 1 varspec])
    FullCAcsl.FullCAcslParser.Abs.SimpleSpec fullidentifier -> prPrec i 1 (concatD [prt 0 fullidentifier])
    FullCAcsl.FullCAcslParser.Abs.ArraySpec varspec arraysize -> prPrec i 1 (concatD [prt 1 varspec, doc (showString "["), prt 0 arraysize, doc (showString "]")])

instance Print FullCAcsl.FullCAcslParser.Abs.Stars where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.Star -> prPrec i 0 (concatD [doc (showString "*")])

instance Print [FullCAcsl.FullCAcslParser.Abs.Stars] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.ArraySize where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.IntConstArraySize n -> prPrec i 0 (concatD [prt 0 n])
    FullCAcsl.FullCAcslParser.Abs.SomeArraySize fullidentifier -> prPrec i 0 (concatD [prt 0 fullidentifier])
    FullCAcsl.FullCAcslParser.Abs.NoSize -> prPrec i 0 (concatD [])

instance Print FullCAcsl.FullCAcslParser.Abs.OptLabel where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.OptLabelOne optlabellist -> prPrec i 1 (concatD [prt 0 optlabellist])
    FullCAcsl.FullCAcslParser.Abs.OptLabelTwo optlabellist -> prPrec i 2 (concatD [prt 0 optlabellist])

instance Print FullCAcsl.FullCAcslParser.Abs.OptLabelList where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoLableList -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.LableList labelnames -> prPrec i 0 (concatD [doc (showString "{"), prt 0 labelnames, doc (showString "}")])

instance Print FullCAcsl.FullCAcslParser.Abs.LabelName where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.LableName anyidentifier -> prPrec i 0 (concatD [prt 0 anyidentifier])

instance Print [FullCAcsl.FullCAcslParser.Abs.LabelName] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.Range where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.LexprRange lexproption1 lexproption2 -> prPrec i 0 (concatD [prt 0 lexproption1, doc (showString ".."), prt 0 lexproption2])

instance Print FullCAcsl.FullCAcslParser.Abs.LexprOption where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoLexprOption -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomeLexprOption lexpr -> prPrec i 0 (concatD [prt 0 lexpr])

instance Print FullCAcsl.FullCAcslParser.Abs.AnyIdentifier where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleIdentifierAny identifier -> prPrec i 0 (concatD [prt 0 identifier])

instance Print FullCAcsl.FullCAcslParser.Abs.PostCond where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.EnsuresKeyWord -> prPrec i 0 (concatD [doc (showString "ensures")])
    FullCAcsl.FullCAcslParser.Abs.ExitsKeyWord -> prPrec i 0 (concatD [doc (showString "exits")])
    FullCAcsl.FullCAcslParser.Abs.BreaksKeyWord -> prPrec i 0 (concatD [doc (showString "breaks")])
    FullCAcsl.FullCAcslParser.Abs.ContinuesKeyWord -> prPrec i 0 (concatD [doc (showString "continues")])
    FullCAcsl.FullCAcslParser.Abs.ReturnsKeyWord -> prPrec i 0 (concatD [doc (showString "returns")])
    FullCAcsl.FullCAcslParser.Abs.CheckEnsuresKeyWord -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "ensures")])
    FullCAcsl.FullCAcslParser.Abs.CheckExitsKeyWord -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "exits")])
    FullCAcsl.FullCAcslParser.Abs.CheckBreaksKeyWord -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "breaks")])
    FullCAcsl.FullCAcslParser.Abs.CheckContinuesKeyWord -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "continues")])
    FullCAcsl.FullCAcslParser.Abs.CheckReturnsKeyWord -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "returns")])
    FullCAcsl.FullCAcslParser.Abs.AdmitEnsuresKeyWord -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "ensures")])
    FullCAcsl.FullCAcslParser.Abs.AdmitExitsKeyWord -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "exits")])
    FullCAcsl.FullCAcslParser.Abs.AdmitBreaksKeyWord -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "breaks")])
    FullCAcsl.FullCAcslParser.Abs.AdmitContinuesKeyWord -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "continues")])
    FullCAcsl.FullCAcslParser.Abs.AdmitReturnsKeyWord -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "returns")])

instance Print FullCAcsl.FullCAcslParser.Abs.FullIdentifier where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleIdentifierFull identifier -> prPrec i 0 (concatD [prt 0 identifier])

instance Print [FullCAcsl.FullCAcslParser.Abs.FullIdentifier] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print FullCAcsl.FullCAcslParser.Abs.Identifier where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.IdentifierIdent id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print FullCAcsl.FullCAcslParser.Abs.TypeSpecSimple where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleIntegerKeyWord -> prPrec i 0 (concatD [doc (showString "integer")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleRealKeyWord -> prPrec i 0 (concatD [doc (showString "real")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleBooleanKeyWord -> prPrec i 0 (concatD [doc (showString "boolean")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleVoidKeyWord -> prPrec i 0 (concatD [doc (showString "void")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleBoolKeyWord -> prPrec i 0 (concatD [doc (showString "_Bool")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleCharKeyWord -> prPrec i 0 (concatD [doc (showString "char")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleIntKeyWord -> prPrec i 0 (concatD [doc (showString "int")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleDoubleKeyWord -> prPrec i 0 (concatD [doc (showString "double")])
    FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleLongDoubleKeyWord -> prPrec i 0 (concatD [doc (showString "long"), doc (showString "double")])

instance Print FullCAcsl.FullCAcslParser.Abs.LogicPTreeAnnot where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.AnAnnotation annotation -> prPrec i 0 (concatD [prt 0 annotation])

instance Print FullCAcsl.FullCAcslParser.Abs.Annotation where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.LoopAnnotation loopannotstack -> prPrec i 0 (concatD [prt 0 loopannotstack])

instance Print FullCAcsl.FullCAcslParser.Abs.LoopAnnotStack where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.LoopAnnotStackInvariant loopinvariant loopannotopt -> prPrec i 0 (concatD [prt 0 loopinvariant, prt 0 loopannotopt])
    FullCAcsl.FullCAcslParser.Abs.LoopAnnotStackEffects loopeffects loopannotopt -> prPrec i 0 (concatD [prt 0 loopeffects, prt 0 loopannotopt])
    FullCAcsl.FullCAcslParser.Abs.LoopAnnotStackVariant loopvariant loopannotopt -> prPrec i 0 (concatD [prt 0 loopvariant, prt 0 loopannotopt])

instance Print FullCAcsl.FullCAcslParser.Abs.LoopAnnotOpt where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.NoLoopAnnot -> prPrec i 0 (concatD [])
    FullCAcsl.FullCAcslParser.Abs.SomeLoopAnnot loopannotstack -> prPrec i 0 (concatD [prt 0 loopannotstack])

instance Print FullCAcsl.FullCAcslParser.Abs.LoopInvariant where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleLoopInvariant lexpr -> prPrec i 0 (concatD [doc (showString "loop"), doc (showString "invariant"), prt 0 lexpr, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.CheckLoopInvariant lexpr -> prPrec i 0 (concatD [doc (showString "check"), doc (showString "loop"), doc (showString "invariant"), prt 0 lexpr, doc (showString ";")])
    FullCAcsl.FullCAcslParser.Abs.AdmitLoopInvariant lexpr -> prPrec i 0 (concatD [doc (showString "admit"), doc (showString "loop"), doc (showString "invariant"), prt 0 lexpr, doc (showString ";")])

instance Print FullCAcsl.FullCAcslParser.Abs.LoopVariant where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.SimpleLoopVariant variant -> prPrec i 0 (concatD [doc (showString "loop"), doc (showString "variant"), prt 0 variant, doc (showString ";")])

instance Print FullCAcsl.FullCAcslParser.Abs.LoopEffects where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.LoopAssigns assigns -> prPrec i 0 (concatD [doc (showString "loop"), doc (showString "assigns"), prt 0 assigns, doc (showString ";")])

instance Print FullCAcsl.FullCAcslParser.Abs.Variant where
  prt i = \case
    FullCAcsl.FullCAcslParser.Abs.ForVariant lexpr anyidentifier -> prPrec i 0 (concatD [prt 0 lexpr, doc (showString "for"), prt 0 anyidentifier])
    FullCAcsl.FullCAcslParser.Abs.LexprVariant lexpr -> prPrec i 0 (concatD [prt 0 lexpr])
