-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module FullCAcsl.FullCAcslParser.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified FullCAcsl.FullCAcslParser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: FullCAcsl.FullCAcslParser.Abs.Ident -> Result
transIdent x = case x of
  FullCAcsl.FullCAcslParser.Abs.Ident string -> failure x

transSIGNED :: FullCAcsl.FullCAcslParser.Abs.SIGNED -> Result
transSIGNED x = case x of
  FullCAcsl.FullCAcslParser.Abs.SIGNED string -> failure x

transLBRACE :: FullCAcsl.FullCAcslParser.Abs.LBRACE -> Result
transLBRACE x = case x of
  FullCAcsl.FullCAcslParser.Abs.LBRACE string -> failure x

transRBRACE :: FullCAcsl.FullCAcslParser.Abs.RBRACE -> Result
transRBRACE x = case x of
  FullCAcsl.FullCAcslParser.Abs.RBRACE string -> failure x

transCONST :: FullCAcsl.FullCAcslParser.Abs.CONST -> Result
transCONST x = case x of
  FullCAcsl.FullCAcslParser.Abs.CONST string -> failure x

transRESTRICT :: FullCAcsl.FullCAcslParser.Abs.RESTRICT -> Result
transRESTRICT x = case x of
  FullCAcsl.FullCAcslParser.Abs.RESTRICT string -> failure x

transVOLATILE :: FullCAcsl.FullCAcslParser.Abs.VOLATILE -> Result
transVOLATILE x = case x of
  FullCAcsl.FullCAcslParser.Abs.VOLATILE string -> failure x

transBLOCKATTRIBUTE :: FullCAcsl.FullCAcslParser.Abs.BLOCKATTRIBUTE -> Result
transBLOCKATTRIBUTE x = case x of
  FullCAcsl.FullCAcslParser.Abs.BLOCKATTRIBUTE string -> failure x

transLBRACKET :: FullCAcsl.FullCAcslParser.Abs.LBRACKET -> Result
transLBRACKET x = case x of
  FullCAcsl.FullCAcslParser.Abs.LBRACKET string -> failure x

transRBRACKET :: FullCAcsl.FullCAcslParser.Abs.RBRACKET -> Result
transRBRACKET x = case x of
  FullCAcsl.FullCAcslParser.Abs.RBRACKET string -> failure x

transProgram :: FullCAcsl.FullCAcslParser.Abs.Program -> Result
transProgram x = case x of
  FullCAcsl.FullCAcslParser.Abs.AProgram globals -> failure x

transGlobals :: FullCAcsl.FullCAcslParser.Abs.Globals -> Result
transGlobals x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoGlobals -> failure x
  FullCAcsl.FullCAcslParser.Abs.SimpleGlobals global globals -> failure x
  FullCAcsl.FullCAcslParser.Abs.SemiColonGlobals globals -> failure x

transGlobal :: FullCAcsl.FullCAcslParser.Abs.Global -> Result
transGlobal x = case x of
  FullCAcsl.FullCAcslParser.Abs.GlobalsFunctionDef functiondef -> failure x
  FullCAcsl.FullCAcslParser.Abs.GlobalsDeclataion declaration -> failure x

transFunctionDef :: FullCAcsl.FullCAcslParser.Abs.FunctionDef -> Result
transFunctionDef x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleFunctionDef functiondefstart block -> failure x
  FullCAcsl.FullCAcslParser.Abs.FunctionDefSpec acslprogram functiondefstart block -> failure x

transFunctionDefStart :: FullCAcsl.FullCAcslParser.Abs.FunctionDefStart -> Result
transFunctionDefStart x = case x of
  FullCAcsl.FullCAcslParser.Abs.FunctionDefStartDeclarator declspeclist declarator -> failure x

transDeclSpecList :: FullCAcsl.FullCAcslParser.Abs.DeclSpecList -> Result
transDeclSpecList x = case x of
  FullCAcsl.FullCAcslParser.Abs.DeclSpecTypeSpec typespec -> failure x
  FullCAcsl.FullCAcslParser.Abs.DeclSpecTypeSpecNext typespec declspeclistnonamed -> failure x

transDeclSpecListNoNamed :: FullCAcsl.FullCAcslParser.Abs.DeclSpecListNoNamed -> Result
transDeclSpecListNoNamed x = case x of
  FullCAcsl.FullCAcslParser.Abs.DeclSpecNoNamedTypeSpec typespec -> failure x
  FullCAcsl.FullCAcslParser.Abs.DeclSpecNoNamedTypeSpecNext typespec declspeclistnonamed -> failure x

transTypeSpec :: FullCAcsl.FullCAcslParser.Abs.TypeSpec -> Result
transTypeSpec x = case x of
  FullCAcsl.FullCAcslParser.Abs.TypeSpecVoidKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecCharKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecBoolKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecShortKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecInt32KeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecIntKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSizeTKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecLongKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecInt64KeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecFloatKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecDoubleKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSignedKeyWord signed -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecUnsignedKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.StructId idortypename -> failure x
  FullCAcsl.FullCAcslParser.Abs.StructIdBraces idortypename structdecllist -> failure x
  FullCAcsl.FullCAcslParser.Abs.StructBraces structdecllist -> failure x

transDeclarator :: FullCAcsl.FullCAcslParser.Abs.Declarator -> Result
transDeclarator x = case x of
  FullCAcsl.FullCAcslParser.Abs.ADeclarator pointeropt directdecl attributeswithasm -> failure x

transPointerOpt :: FullCAcsl.FullCAcslParser.Abs.PointerOpt -> Result
transPointerOpt x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoPointer -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomePointer attributes pointeropt -> failure x

transDirectDecl :: FullCAcsl.FullCAcslParser.Abs.DirectDecl -> Result
transDirectDecl x = case x of
  FullCAcsl.FullCAcslParser.Abs.DirectDeclIdTypename idortypename -> failure x
  FullCAcsl.FullCAcslParser.Abs.DirectDeclGhostParam directdecl ghostparameteropt -> failure x
  FullCAcsl.FullCAcslParser.Abs.DirectDeclGhostRestParParam directdecl restparlist ghostparameteropt -> failure x

transAttributesWithAsm :: FullCAcsl.FullCAcslParser.Abs.AttributesWithAsm -> Result
transAttributesWithAsm x = case x of
  FullCAcsl.FullCAcslParser.Abs.EmptyAttrWithASM -> failure x

transRestParList :: FullCAcsl.FullCAcslParser.Abs.RestParList -> Result
transRestParList x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleParameterDecl parameterdecls -> failure x

transParameterDecl :: FullCAcsl.FullCAcslParser.Abs.ParameterDecl -> Result
transParameterDecl x = case x of
  FullCAcsl.FullCAcslParser.Abs.ParameterDeclSpecDeclarator declspeclist declarator -> failure x
  FullCAcsl.FullCAcslParser.Abs.ParameterDeclSpec declspeclist -> failure x
  FullCAcsl.FullCAcslParser.Abs.ParameterDeclPar parameterdecl -> failure x

transGhostParameterOpt :: FullCAcsl.FullCAcslParser.Abs.GhostParameterOpt -> Result
transGhostParameterOpt x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoGhostParameter -> failure x

transIdOrTypename :: FullCAcsl.FullCAcslParser.Abs.IdOrTypename -> Result
transIdOrTypename x = case x of
  FullCAcsl.FullCAcslParser.Abs.IdTypename idortypenameasid -> failure x

transIdOrTypenameAsId :: FullCAcsl.FullCAcslParser.Abs.IdOrTypenameAsId -> Result
transIdOrTypenameAsId x = case x of
  FullCAcsl.FullCAcslParser.Abs.IdOrTypenameAsIdIdentifier ident -> failure x

transDeclaration :: FullCAcsl.FullCAcslParser.Abs.Declaration -> Result
transDeclaration x = case x of
  FullCAcsl.FullCAcslParser.Abs.DeclSpecInitDecl declspeclist declandinitdeclattrlist -> failure x
  FullCAcsl.FullCAcslParser.Abs.DeclSpec declspeclist -> failure x
  FullCAcsl.FullCAcslParser.Abs.SpecDeclSpecInitDecl acslprogram declspeclist declandinitdeclattrlist -> failure x
  FullCAcsl.FullCAcslParser.Abs.SpecDeclSpec acslprogram declspeclist -> failure x

transDeclAndInitDeclAttrList :: FullCAcsl.FullCAcslParser.Abs.DeclAndInitDeclAttrList -> Result
transDeclAndInitDeclAttrList x = case x of
  FullCAcsl.FullCAcslParser.Abs.InitDeclaration initdeclarator -> failure x
  FullCAcsl.FullCAcslParser.Abs.InitDeclarationWithAttr initdeclarator initdeclaratorattrs -> failure x

transInitDeclaratorAttr :: FullCAcsl.FullCAcslParser.Abs.InitDeclaratorAttr -> Result
transInitDeclaratorAttr x = case x of
  FullCAcsl.FullCAcslParser.Abs.InitDeclaratorAttribute initdeclarator -> failure x

transInitDeclarator :: FullCAcsl.FullCAcslParser.Abs.InitDeclarator -> Result
transInitDeclarator x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleInitDeclarator declarator -> failure x

transStructDeclList :: FullCAcsl.FullCAcslParser.Abs.StructDeclList -> Result
transStructDeclList x = case x of
  FullCAcsl.FullCAcslParser.Abs.EmptyStructDecl -> failure x
  FullCAcsl.FullCAcslParser.Abs.DeclSpecStructDecl declspeclist structdecllist -> failure x
  FullCAcsl.FullCAcslParser.Abs.SemicolonStructDecl structdecllist -> failure x
  FullCAcsl.FullCAcslParser.Abs.SpecFieldDeclStructDecl declspeclist fielddecls structdecllist -> failure x

transFieldDecl :: FullCAcsl.FullCAcslParser.Abs.FieldDecl -> Result
transFieldDecl x = case x of
  FullCAcsl.FullCAcslParser.Abs.FieldDeclDeclarator declarator -> failure x

transAttribute :: FullCAcsl.FullCAcslParser.Abs.Attribute -> Result
transAttribute x = case x of
  FullCAcsl.FullCAcslParser.Abs.AttributeConst const -> failure x

transBlock :: FullCAcsl.FullCAcslParser.Abs.Block -> Result
transBlock x = case x of
  FullCAcsl.FullCAcslParser.Abs.ABlock blockattrs blockelements -> failure x

transBlockAttrs :: FullCAcsl.FullCAcslParser.Abs.BlockAttrs -> Result
transBlockAttrs x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoBlockAttrs -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeBlockAttrs blockattribute attrs -> failure x

transBlockElement :: FullCAcsl.FullCAcslParser.Abs.BlockElement -> Result
transBlockElement x = case x of
  FullCAcsl.FullCAcslParser.Abs.DeclarationElement declaration -> failure x
  FullCAcsl.FullCAcslParser.Abs.StatementElement statement -> failure x

transStatement :: FullCAcsl.FullCAcslParser.Abs.Statement -> Result
transStatement x = case x of
  FullCAcsl.FullCAcslParser.Abs.SemicolonStatement -> failure x
  FullCAcsl.FullCAcslParser.Abs.SpecStatement acslprogram annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.ExprsStatement expressions -> failure x
  FullCAcsl.FullCAcslParser.Abs.BlockStatement block -> failure x
  FullCAcsl.FullCAcslParser.Abs.IfStatement expressions annotatedstmt elsepart -> failure x
  FullCAcsl.FullCAcslParser.Abs.SwitchStatement expressions annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.WhileStatement expressions annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.ForStatement forclause optexpression1 optexpression2 annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.CaseStatement expression annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.CaseSliceStatement expression1 expression2 annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.DefaultStatement annotatedstmt -> failure x
  FullCAcsl.FullCAcslParser.Abs.EmptyReturnStatement -> failure x
  FullCAcsl.FullCAcslParser.Abs.ReturnStatement expressions -> failure x
  FullCAcsl.FullCAcslParser.Abs.BreakStatement -> failure x
  FullCAcsl.FullCAcslParser.Abs.ContinueStatement -> failure x

transForClause :: FullCAcsl.FullCAcslParser.Abs.ForClause -> Result
transForClause x = case x of
  FullCAcsl.FullCAcslParser.Abs.ForClauseExpression optexpression -> failure x
  FullCAcsl.FullCAcslParser.Abs.ForClauseDeclaration declaration -> failure x

transAttr :: FullCAcsl.FullCAcslParser.Abs.Attr -> Result
transAttr x = case x of
  FullCAcsl.FullCAcslParser.Abs.AnAttr attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.TernaryCond attr1 attr2 attr3 -> failure x
  FullCAcsl.FullCAcslParser.Abs.Or attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.And attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BitOr attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.Xor attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BitAnd attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.EqualEqual attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.NotEqual attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.Less attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.Greater attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.LessEqual attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.GreaterEqual attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.LeftShiftOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.RightShiftOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.AddOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.SubOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.MultOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.DivOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.ModOp attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.PlusUnaryAttr attr -> failure x
  FullCAcsl.FullCAcslParser.Abs.MinusUnaryAttr attr -> failure x
  FullCAcsl.FullCAcslParser.Abs.MultUnaryAttr attr -> failure x
  FullCAcsl.FullCAcslParser.Abs.AmpUnaryAttr attr -> failure x
  FullCAcsl.FullCAcslParser.Abs.NotUnaryAttr attr -> failure x
  FullCAcsl.FullCAcslParser.Abs.TildeUnaryAttr attr -> failure x
  FullCAcsl.FullCAcslParser.Abs.FuncationCall idortypenameasid attrs -> failure x
  FullCAcsl.FullCAcslParser.Abs.ProcedureCall idortypenameasid -> failure x
  FullCAcsl.FullCAcslParser.Abs.ArrowAttr attr idortypename -> failure x
  FullCAcsl.FullCAcslParser.Abs.DotAttr attr idortypename -> failure x
  FullCAcsl.FullCAcslParser.Abs.ArrayAttr attr1 attr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BasicAttr basicattribute -> failure x

transBasicAttribute :: FullCAcsl.FullCAcslParser.Abs.BasicAttribute -> Result
transBasicAttribute x = case x of
  FullCAcsl.FullCAcslParser.Abs.BasicAttrConsInt integer -> failure x
  FullCAcsl.FullCAcslParser.Abs.BasicAttrConsFloat double -> failure x

transAnnotatedStmt :: FullCAcsl.FullCAcslParser.Abs.AnnotatedStmt -> Result
transAnnotatedStmt x = case x of
  FullCAcsl.FullCAcslParser.Abs.AnnotatedStatement statement -> failure x

transElsePart :: FullCAcsl.FullCAcslParser.Abs.ElsePart -> Result
transElsePart x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoElsePart -> failure x
  FullCAcsl.FullCAcslParser.Abs.SimpleElsePart annotatedstmt -> failure x

transOptExpression :: FullCAcsl.FullCAcslParser.Abs.OptExpression -> Result
transOptExpression x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoExpression -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeExpression expressions -> failure x

transExpression :: FullCAcsl.FullCAcslParser.Abs.Expression -> Result
transExpression x = case x of
  FullCAcsl.FullCAcslParser.Abs.AssignmentExpr assignexpr -> failure x

transAssignExpr :: FullCAcsl.FullCAcslParser.Abs.AssignExpr -> Result
transAssignExpr x = case x of
  FullCAcsl.FullCAcslParser.Abs.EqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.PlusEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.MinusEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.MultEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.DivEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.ModEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.AndEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.OrEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.XorEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.LeftShiftEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.RightShiftEqAssignExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.TernaryCondExpr assignexpr1 optexpression assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.OrExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.AndExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BitOrExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BitXorExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BitAndExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.EqExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.NotEqExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.LessExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.GreaterExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.LessEqualExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.GreaterEqualExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.LeftShiftExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.RightShiftExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.PlusExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.MinusExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.MulsExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.DivExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.ModExpr assignexpr1 assignexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.CastExpr typename assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprPlusPlus assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprMinusMinus assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprPlus assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprMinus assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprMult assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprAmp assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprNot assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprTilde assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnaryExprAddress idortypenameasid -> failure x
  FullCAcsl.FullCAcslParser.Abs.BracketsPostfixExpression assignexpr expressions -> failure x
  FullCAcsl.FullCAcslParser.Abs.DotPostfixExpression assignexpr idortypename -> failure x
  FullCAcsl.FullCAcslParser.Abs.ArrowPostfixExpression assignexpr idortypename -> failure x
  FullCAcsl.FullCAcslParser.Abs.PlusPlusPostfixExpression assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.MinusMinusPostfixExpression assignexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.IdentifierPrimaryExpression ident -> failure x
  FullCAcsl.FullCAcslParser.Abs.ConstantPrimaryExpressin constant -> failure x
  FullCAcsl.FullCAcslParser.Abs.CommaExpressionPrimaryExpressin expressions -> failure x
  FullCAcsl.FullCAcslParser.Abs.BlockPrimaryExpressin block -> failure x

transConstant :: FullCAcsl.FullCAcslParser.Abs.Constant -> Result
transConstant x = case x of
  FullCAcsl.FullCAcslParser.Abs.ConstantInt integer -> failure x
  FullCAcsl.FullCAcslParser.Abs.ConstantFloat double -> failure x
  FullCAcsl.FullCAcslParser.Abs.ConstantChar char -> failure x

transTypeName :: FullCAcsl.FullCAcslParser.Abs.TypeName -> Result
transTypeName x = case x of
  FullCAcsl.FullCAcslParser.Abs.TypeNameDeclSpecList declspeclist -> failure x

transACSLProgram :: FullCAcsl.FullCAcslParser.Abs.ACSLProgram -> Result
transACSLProgram x = case x of
  FullCAcsl.FullCAcslParser.Abs.AnnotProgram annot -> failure x
  FullCAcsl.FullCAcslParser.Abs.AnnotationProgram logicptreeannot -> failure x

transAnnot :: FullCAcsl.FullCAcslParser.Abs.Annot -> Result
transAnnot x = case x of
  FullCAcsl.FullCAcslParser.Abs.CodeAnnot codeannot -> failure x

transCode_Annot :: FullCAcsl.FullCAcslParser.Abs.Code_Annot -> Result
transCode_Annot x = case x of
  FullCAcsl.FullCAcslParser.Abs.CodeAnnotContract contract -> failure x

transContract :: FullCAcsl.FullCAcslParser.Abs.Contract -> Result
transContract x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleContract requires terminates decreases simpleclauses behaviors completeordisjoint -> failure x

transRequires :: FullCAcsl.FullCAcslParser.Abs.Requires -> Result
transRequires x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoRequires -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeRequires nerequires -> failure x

transNERequires :: FullCAcsl.FullCAcslParser.Abs.NERequires -> Result
transNERequires x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleRequires lexpr requires -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckRequires lexpr requires -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdimtRequires lexpr requires -> failure x

transTerminates :: FullCAcsl.FullCAcslParser.Abs.Terminates -> Result
transTerminates x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoTerminate -> failure x

transDecreases :: FullCAcsl.FullCAcslParser.Abs.Decreases -> Result
transDecreases x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoDecreases -> failure x

transSimpleClauses :: FullCAcsl.FullCAcslParser.Abs.SimpleClauses -> Result
transSimpleClauses x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoSimpleClauses -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeSimpleClauses nesimpleclauses -> failure x

transNESimpleClauses :: FullCAcsl.FullCAcslParser.Abs.NESimpleClauses -> Result
transNESimpleClauses x = case x of
  FullCAcsl.FullCAcslParser.Abs.PostCondSimpleClauses postcond lexpr simpleclauses -> failure x
  FullCAcsl.FullCAcslParser.Abs.AssignsSimpleClauses assigns simpleclauses -> failure x

transAssigns :: FullCAcsl.FullCAcslParser.Abs.Assigns -> Result
transAssigns x = case x of
  FullCAcsl.FullCAcslParser.Abs.AssignZone zones -> failure x
  FullCAcsl.FullCAcslParser.Abs.AssignZoneFromZone lexprs zones -> failure x

transZones :: FullCAcsl.FullCAcslParser.Abs.Zones -> Result
transZones x = case x of
  FullCAcsl.FullCAcslParser.Abs.SomeZone lexprs -> failure x
  FullCAcsl.FullCAcslParser.Abs.NoZone -> failure x

transBehaviors :: FullCAcsl.FullCAcslParser.Abs.Behaviors -> Result
transBehaviors x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoBehaviors -> failure x

transCompleteOrDisjoint :: FullCAcsl.FullCAcslParser.Abs.CompleteOrDisjoint -> Result
transCompleteOrDisjoint x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoComplDisj -> failure x

transLexpr :: FullCAcsl.FullCAcslParser.Abs.Lexpr -> Result
transLexpr x = case x of
  FullCAcsl.FullCAcslParser.Abs.ImplLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.IffLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.OrLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.AndLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.HatHatLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.RelationLexpr lexpr1 lexprrelinners relation lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.BinderLexpr lexprbinder -> failure x
  FullCAcsl.FullCAcslParser.Abs.NotBinderLexpr lexprbinder -> failure x
  FullCAcsl.FullCAcslParser.Abs.TrueLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.FalseLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.ValidLexpr optlabel lexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.AutomaticLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.DynamicLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.RegisterLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.StaticLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.UnallocatedLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.NullLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.LexprIntConst integer -> failure x
  FullCAcsl.FullCAcslParser.Abs.LexprFloatConst double -> failure x
  FullCAcsl.FullCAcslParser.Abs.LexprStringConst string -> failure x
  FullCAcsl.FullCAcslParser.Abs.AddLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.SubtrLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.SquaresRangeLexpr lexpr range -> failure x
  FullCAcsl.FullCAcslParser.Abs.SquaresLexpr lexpr1 lexpr2 -> failure x
  FullCAcsl.FullCAcslParser.Abs.SeparatedLexpr lexprs -> failure x
  FullCAcsl.FullCAcslParser.Abs.FullIdParenLexpr fullidentifier lexprs -> failure x
  FullCAcsl.FullCAcslParser.Abs.FullId fullidentifier -> failure x
  FullCAcsl.FullCAcslParser.Abs.PiLexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.ParenRangeLexpr range -> failure x

transLexprRelInner :: FullCAcsl.FullCAcslParser.Abs.LexprRelInner -> Result
transLexprRelInner x = case x of
  FullCAcsl.FullCAcslParser.Abs.RelInnerLexpr relation lexpr -> failure x

transRelation :: FullCAcsl.FullCAcslParser.Abs.Relation -> Result
transRelation x = case x of
  FullCAcsl.FullCAcslParser.Abs.LessRel -> failure x
  FullCAcsl.FullCAcslParser.Abs.GreaterRel -> failure x
  FullCAcsl.FullCAcslParser.Abs.LessEqRel -> failure x
  FullCAcsl.FullCAcslParser.Abs.GreaterEqRel -> failure x
  FullCAcsl.FullCAcslParser.Abs.EqRel -> failure x
  FullCAcsl.FullCAcslParser.Abs.NotEqRel -> failure x

transLexprBinder :: FullCAcsl.FullCAcslParser.Abs.LexprBinder -> Result
transLexprBinder x = case x of
  FullCAcsl.FullCAcslParser.Abs.ForallBinderLexpr binders lexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.ExistBinderLexpr binders lexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.LambdaBinderLexpr binders lexpr -> failure x

transBinders :: FullCAcsl.FullCAcslParser.Abs.Binders -> Result
transBinders x = case x of
  FullCAcsl.FullCAcslParser.Abs.TheBinders typespecoftypename varspec bindersreentrances -> failure x

transTypeSpecOFTYPENAME :: FullCAcsl.FullCAcslParser.Abs.TypeSpecOFTYPENAME -> Result
transTypeSpecOFTYPENAME x = case x of
  FullCAcsl.FullCAcslParser.Abs.TypeSpecTYPENAME ident -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleFromTypenameTypeSpec typespecsimple -> failure x

transBindersReentrance :: FullCAcsl.FullCAcslParser.Abs.BindersReentrance -> Result
transBindersReentrance x = case x of
  FullCAcsl.FullCAcslParser.Abs.BindersReentranceDeclSpec typespecoftypename varspec -> failure x
  FullCAcsl.FullCAcslParser.Abs.BindersReentranceVarSpec varspec -> failure x

transVarSpec :: FullCAcsl.FullCAcslParser.Abs.VarSpec -> Result
transVarSpec x = case x of
  FullCAcsl.FullCAcslParser.Abs.StartVarSpec starss varspec -> failure x
  FullCAcsl.FullCAcslParser.Abs.SimpleSpec fullidentifier -> failure x
  FullCAcsl.FullCAcslParser.Abs.ArraySpec varspec arraysize -> failure x

transStars :: FullCAcsl.FullCAcslParser.Abs.Stars -> Result
transStars x = case x of
  FullCAcsl.FullCAcslParser.Abs.Star -> failure x

transArraySize :: FullCAcsl.FullCAcslParser.Abs.ArraySize -> Result
transArraySize x = case x of
  FullCAcsl.FullCAcslParser.Abs.IntConstArraySize integer -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeArraySize fullidentifier -> failure x
  FullCAcsl.FullCAcslParser.Abs.NoSize -> failure x

transOptLabel :: FullCAcsl.FullCAcslParser.Abs.OptLabel -> Result
transOptLabel x = case x of
  FullCAcsl.FullCAcslParser.Abs.OptLabelOne optlabellist -> failure x
  FullCAcsl.FullCAcslParser.Abs.OptLabelTwo optlabellist -> failure x

transOptLabelList :: FullCAcsl.FullCAcslParser.Abs.OptLabelList -> Result
transOptLabelList x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoLableList -> failure x
  FullCAcsl.FullCAcslParser.Abs.LableList labelnames -> failure x

transLabelName :: FullCAcsl.FullCAcslParser.Abs.LabelName -> Result
transLabelName x = case x of
  FullCAcsl.FullCAcslParser.Abs.LableName anyidentifier -> failure x

transRange :: FullCAcsl.FullCAcslParser.Abs.Range -> Result
transRange x = case x of
  FullCAcsl.FullCAcslParser.Abs.LexprRange lexproption1 lexproption2 -> failure x

transLexprOption :: FullCAcsl.FullCAcslParser.Abs.LexprOption -> Result
transLexprOption x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoLexprOption -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeLexprOption lexpr -> failure x

transAnyIdentifier :: FullCAcsl.FullCAcslParser.Abs.AnyIdentifier -> Result
transAnyIdentifier x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleIdentifierAny identifier -> failure x

transPostCond :: FullCAcsl.FullCAcslParser.Abs.PostCond -> Result
transPostCond x = case x of
  FullCAcsl.FullCAcslParser.Abs.EnsuresKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.ExitsKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.BreaksKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.ContinuesKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.ReturnsKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckEnsuresKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckExitsKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckBreaksKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckContinuesKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckReturnsKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdmitEnsuresKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdmitExitsKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdmitBreaksKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdmitContinuesKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdmitReturnsKeyWord -> failure x

transFullIdentifier :: FullCAcsl.FullCAcslParser.Abs.FullIdentifier -> Result
transFullIdentifier x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleIdentifierFull identifier -> failure x

transIdentifier :: FullCAcsl.FullCAcslParser.Abs.Identifier -> Result
transIdentifier x = case x of
  FullCAcsl.FullCAcslParser.Abs.IdentifierIdent ident -> failure x

transTypeSpecSimple :: FullCAcsl.FullCAcslParser.Abs.TypeSpecSimple -> Result
transTypeSpecSimple x = case x of
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleIntegerKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleRealKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleBooleanKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleVoidKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleBoolKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleCharKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleIntKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleDoubleKeyWord -> failure x
  FullCAcsl.FullCAcslParser.Abs.TypeSpecSimpleLongDoubleKeyWord -> failure x

transLogicPTreeAnnot :: FullCAcsl.FullCAcslParser.Abs.LogicPTreeAnnot -> Result
transLogicPTreeAnnot x = case x of
  FullCAcsl.FullCAcslParser.Abs.AnAnnotation annotation -> failure x

transAnnotation :: FullCAcsl.FullCAcslParser.Abs.Annotation -> Result
transAnnotation x = case x of
  FullCAcsl.FullCAcslParser.Abs.LoopAnnotation loopannotstack -> failure x

transLoopAnnotStack :: FullCAcsl.FullCAcslParser.Abs.LoopAnnotStack -> Result
transLoopAnnotStack x = case x of
  FullCAcsl.FullCAcslParser.Abs.LoopAnnotStackInvariant loopinvariant loopannotopt -> failure x
  FullCAcsl.FullCAcslParser.Abs.LoopAnnotStackEffects loopeffects loopannotopt -> failure x
  FullCAcsl.FullCAcslParser.Abs.LoopAnnotStackVariant loopvariant loopannotopt -> failure x

transLoopAnnotOpt :: FullCAcsl.FullCAcslParser.Abs.LoopAnnotOpt -> Result
transLoopAnnotOpt x = case x of
  FullCAcsl.FullCAcslParser.Abs.NoLoopAnnot -> failure x
  FullCAcsl.FullCAcslParser.Abs.SomeLoopAnnot loopannotstack -> failure x

transLoopInvariant :: FullCAcsl.FullCAcslParser.Abs.LoopInvariant -> Result
transLoopInvariant x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleLoopInvariant lexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.CheckLoopInvariant lexpr -> failure x
  FullCAcsl.FullCAcslParser.Abs.AdmitLoopInvariant lexpr -> failure x

transLoopVariant :: FullCAcsl.FullCAcslParser.Abs.LoopVariant -> Result
transLoopVariant x = case x of
  FullCAcsl.FullCAcslParser.Abs.SimpleLoopVariant variant -> failure x

transLoopEffects :: FullCAcsl.FullCAcslParser.Abs.LoopEffects -> Result
transLoopEffects x = case x of
  FullCAcsl.FullCAcslParser.Abs.LoopAssigns assigns -> failure x

transVariant :: FullCAcsl.FullCAcslParser.Abs.Variant -> Result
transVariant x = case x of
  FullCAcsl.FullCAcslParser.Abs.ForVariant lexpr anyidentifier -> failure x
  FullCAcsl.FullCAcslParser.Abs.LexprVariant lexpr -> failure x
